### ISSUE TITLE
[Question]: How can I create a 'all-in-one' RAG pipeline?

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10317]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I am thinking of creating a 'all-in-one' RAG pipeline where the LLM can decide which query engines to use, depending on the query itself.

I am using a open-source LLM `Zephyr 7b alpha` and `React agents` don't seem to work very well

I would like to create a query tool, where for non-complex query `Query: What are the documents regarding?` , it would use a 'naive' top K retriever approach. However, for complex queries such as `Query: Compare the students, rank them by GPA`,  it would use the `SubQuestionQueryEngine`.  

In fact, I am also thinking how to add a step, to reduce the amount of sub-questions generated by the `SubQuestionQueryEngine`. ( Please also advise on an approach regarding that )

How do I go about it regarding this? Thanks in advance!

**Comment by nerdai** [comment]
Hi @GxTeo,

Yes, unfortunately it has been our experience as well that open-source LLMs don't work too well with ReAct framework. We hypothesize that its likely due to their lack of tool-use fine-tuning — GPT models, on the other hand, are very good at this.

In terms of your "all-in-one" query engine, it sounds like you may need the generator (or another LLM) to play an active role in the retrieval. We have the Router Query Engine that may be of use to you here.

[Router Query Engine](https://docs.llamaindex.ai/en/stable/examples/query_engine/RouterQueryEngine.html)
