### ISSUE TITLE
[Question]: If a markdown table is too big, how to make sure the RAG can ingest it?

### ISSUE THREAD

**Issue by xjw1001002** [run-llama/llama_index#10316]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

For example, I have a table in markdown with 10 columns and 24 rows. The result markdown table can be as long as 2000+ tokens. How to handle this type of table?

**Comment by noamzilo** [comment]
Any human encountered this and has an actual battle tested solution?

**Comment by TungLe007** [comment]
@jerryjliu 
can you suggest the configurations for splitting very large tables into smaller chunks? e.g. chunk_size, chunk_overlap, etc.
Thank you!

@dosu-bot: I have an issue with extraction data from markdown.  
- the markdown data is a messy spreadsheet converted from excel file's worksheet.
- the excel has around 30-60 columns and 300+ rows (and may be 500+ rows, each row is a PII data).
- I use TextNode to convert to markdown_node. 
- I use MarkdownElementNodeParse for node_parser.
- then I passed the markdown_node to node_parser via get_nodes_from_documents method.
- then I get base_nodes, objects from node_parser via get_nodes_and_objects method.
when I prompt the names (PII) and their associated data, it only extract around 10 names with their data, it's supposed to extract all 300 names with their associated data. 

Questions:

- What is the right configuration in order to extract all data correctly and stably?
- Do different llm models affect this extraction processing? e.g. gpt4.1 vs sonnet-4. which one yields the better performance to get all data output?
 


```
def get_base_nodes_objects(file_name, sheet_name, llm, num_workers=1, chunk_size=1500, chunk_overlap=150):

    # get markdown content from Excel file
    markdown_content = get_markdown_from_excel(file_name, sheet_name)
    
    # create a TextNode from the markdown content
    markdown_node = TextNode(text=markdown_content)
	node_parser = MarkdownElementNodeParser(llm=llm,
	                                        num_workers=num_workers,
	                                        chunk_size=chunk_size,  			 
	                                        chunk_overlap=chunk_overlap,  		 
	                                        extract_tables=True, 				 
	                                        table_extraction_mode="markdown",  	 
	                                        extract_images=False, 
	                                        include_metadata=True,
	                                        include_prev_next_rel=False
	                                    )

    
    nodes = node_parser.get_nodes_from_documents([markdown_node])
    base_nodes, objects = node_parser.get_nodes_and_objects(nodes)
    
    return base_nodes, objects
```


```
def extract_data(llm, base_nodes, objects, output_cls, query, top_k=15, response_mode="refine"):
    sllm = llm.as_structured_llm(output_cls=output_cls)
    sllm_index = VectorStoreIndex(nodes=base_nodes+objects, llm=sllm)

    sllm_query_engine = sllm_index.as_query_engine(
        similarity_top_k=top_k,
        llm=sllm,
        response_mode=response_mode,   
        response_format=output_cls,  
        streaming=False,   
        use_async=False,   
    )

    response = sllm_query_engine.query(f"{query}")
    instance = response.response
    json_output = instance.model_dump_json(indent=2)
    json_result = json.loads(json_output)
    
    return json_result
```
