### ISSUE TITLE
[Question]: How to retrieve previous questions and answers

### ISSUE THREAD

**Issue by mistoFENG** [run-llama/llama_index#10347]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I tried CondensePlusContextChatEngine, and I noticed the memory parameter. Is this memory a short-term memory? There is a RedisChatStore option. Is this redis just storing my historical questions and answers? If the context of LLM is limited and I want to obtain previous information, what should I do? This RedisChatStore should not be a vector database. Do I still need to save historical conversations to a vector database?

**Comment by mistoFENG** [comment]
Is there any good way to save chat history into a vector database? The examples I see are all about importing files and converting them into documents. Is it feasible to use chat history to instantiate documents? Are there any examples?

**Comment by logan-markewich** [comment]
The memory is just `ChatMemoryBuffer` object, which is a sliding window over the chat history. 
https://docs.llamaindex.ai/en/stable/module_guides/storing/chat_stores.html#simplechatstore

It's not possible to store in a vector db, since there are no vectors.

You are welcome to contribute a new memory object class though 👍🏻
