### ISSUE TITLE
[Question]: Combine AND and OR statements in MetadataFilters

### ISSUE THREAD

**Issue by amindadgar** [run-llama/llama_index#10353]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have some documents saved in postgresql table using llama-index. When creating a query_engine I'm trying to add `AND` filter between my metadata fields and an `OR` filter between a list of filters so I would get exactly the data I need from database. So far I've seen the way to apply filters using

```python
from llama_index.vector_stores import ExactMatchFilter, FilterCondition, MetadataFilters


all_filters = [ .... ] # defining some ExactMatchFilter
filters = MetadataFilters(
      filters=all_filters,
      condition=FilterCondition.OR
)
```

Is there a way to define `FilterCondition.AND` between multiple filters of `all_filters` list (a nested list of filters) and have the for example `OR` condition between the whole `all_filters`?

**Comment by amindadgar** [comment]
The bot's answer is not related to Postgresql database. In `PGVectorStore`, it is using the `MetadataFilters` which they seems not support multiple nested conditions.

**Comment by amindadgar** [comment]
I think this is very related to having no other filters than `ExactMatchFilter`.

**Comment by amindadgar** [comment]
@juleskuehn Thanks for your response. For now, I just did all the retrieval task manually so I could have the combination of filters. I would encourage you to open a PR as more people might have the same problem (I don't have the time myself to do it).

**Comment by juleskuehn** [comment]
@logan-markewich Do you agree with my proposal? If so, I can start on a PR.

**Comment by logan-markewich** [comment]
@juleskuehn if you want to make a pr, go for it 👍 but would need to make sure this doesn't break other vector stores too I think

**Comment by bahrikutlu** [comment]
I had the similar issue with Neo4jPGStore = Neo4jPropertyGraphStore. I got inspired by this post but due to lack of time, I ended up overriding the vector_query method to accept a string. 

I am simply passing the filters as a partial cypher query after creating it programmatically per query. This also helps overcome another limitation I have discovered. The existing filters do not allow comparing two arrays to identify if all elements are equal.

Since the filters can get very complicated, it may be a good option to allow passing filters as a string.
