### ISSUE TITLE
[Feature Request]: Allow for docstore batch insertions

### ISSUE THREAD

**Issue by niels-bosman** [run-llama/llama_index#10437]
### Feature Description

Since Llama index now uses motor for async support for storage backends, users should be able to set a batch size for batch insertions.

### Reason

Not having this is slowing down our application a lot because of big document insertions.

### Value of Feature

This will make applications significantly more performant without any drawback.

**Comment by MarouaneMaatouk** [comment]
Hi, it should be possible to change the batch size:

```python
from llama_index.storage.storage_context import StorageContext
from llama_index.storage.docstore.mongo_docstore import MongoDocumentStore
from llama_index.storage.kvstore.mongodb_kvstore import MongoDBKVStore

mongo_kvstore = MongoDBKVStore.from_uri(...) # or from_host_and_port
docstore = MongoDocumentStore(mongo_kvstore, batch_size=100) # Update the batch size (default value is 1)
storage_context = StorageContext.from_defaults(docstore=docstore)
```

**Comment by VictorAny** [comment]
@MarouaneMaatouk I don't think the batching works for inserts when it comes to vector stores when you using the `insert` function on the vector store index.

I added logging for my vector store when inserting nodes and i'm seeing individual insertions which is dramatically slowing down our system. I think I understand why. Quick explanation. 

1. `insert`
```
    def insert(self, document: Document, **insert_kwargs: Any) -> None:
        """Insert a document."""
        with self._service_context.callback_manager.as_trace("insert"):
            nodes = run_transformations(
                [document],
                self._service_context.transformations,
                show_progress=self._show_progress,
            )

            self.insert_nodes(nodes, **insert_kwargs)
            self.docstore.set_document_hash(document.get_doc_id(), document.hash)
```
This is the primary base index method that the docs tell devs to use per document but looking at the code we can see it calls `insert_nodes` per document and `insert_nodes` then calls the VectorStoreIndex `_insert`. 

For VectorStore index, this calls `_add_nodes_to_index` which then utilizes the `self._insert_batch_size`. The issue here is that the initial `insert` only has one document, so no batching actually occurs. 

You need to use the `VectorStoreIndex.insert_nodes` instead. The documentation needs to update this ASAP as all the examples still use the `insert` which again does no actual batching whatsoever.

For context, making this change took the time for indexing a 7MB file from 2-8 minutes down to 500ms.

My logs before the change:
```
Calling add in vector store with nodes of length 1
```

After:
```
Calling add in vector store with nodes of length 712
```
