### ISSUE TITLE
[Question]: Where to add Cohere x LlamaIndex integration documentation?

### ISSUE THREAD

**Issue by tianjing-li** [run-llama/llama_index#10476]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

We're working at Cohere on adding documentation support for [Cohere's APIs](https://cohere.com). Specifically, we've tested out embed, rerank, and chat+RAG functionality with LlamaIndex. There's several doc improvements and setup guides we could add, maybe even Jupyter notebooks but we are wondering about where best to contribute.

For example, where do the docs here: https://docs.llamaindex.ai/en/stable/api_reference/query/chat_engines/simple_chat_engine.html live? We could potentially add a section here on Cohere quickstarts, or make a repo similar to [mongodb-demo](https://github.com/run-llama/mongodb-demo) that exists already. 

Any insights welcome

**Comment by logan-markewich** [comment]
Hey at @tianjing-li !

I think as far as docs, ensuring there is a working demo in `docs/examples/embeddings` for embeddings and `docs/examples/node_postprocessor` for reranking is a good start

If you wanted to contribute a complete "Cohere <> LlamaIndex" guide, that could definitely go in `docs/examples/query_engine` or `docs/examples/chat_engine`,  -- just have to make sure it gets linked somewhere in the normal `md` documentation so that it shows up in search. Maybe inside `docs/community/integrations` ?

btw -- I know we have a slack channel with cohere, feel free to also reach out on there 👍🏻
