### ISSUE TITLE
[Bug]: Python `get_nodes_from_documents` is notably slow on large text files

### ISSUE THREAD

**Issue by gargn** [run-llama/llama_index#10554]
### Bug Description

We are migrating from TS `getNodesFromDocuments` to Python `get_nodes_from_documents`. TS takes ~3 seconds to generate TextNodes on a ~8MB text file while Python takes ~60 seconds to generate TextNodes on the same file.

One notable observation is `SimpleDirectoryReader` loads the whole ~8MB file into one `Document` object. If we split the text file into multiple `Document` objects, then the same text file generates TextNodes much faster. We tested this by using `nltk.tokenize.sent_tokenize` to put ~50 sentences in each `Document` object and when we passed in the list of documents to `get_nodes_from_documents` it took ~7 seconds to generate TextNodes.

### Version

0.9.39

### Steps to Reproduce

TypeScript code:
```
const reader = new SimpleDirectoryReader();
const docs = (await reader.loadData({ filepath })).map((doc) => {
  doc.metadata.filename = filename;
  return doc;
});
const nodeParser = new SimpleNodeParser({
  textSplitter: new SentenceSplitter({
    chunkOverlap: 32,
    chunkSize: 256,
  }),
});
const nodes = nodeParser.getNodesFromDocuments(docs);
```
  
Python code:
```
reader = SimpleDirectoryReader(input_files=[filepath])
documents = reader.load_data()
splitter = SentenceSplitter.from_defaults(
    chunk_overlap=32,
    chunk_size=256,
)
llama_nodes = splitter.get_nodes_from_documents(documents=documents)
```

Both of these snippets were run over a ~8MB text file.

**Comment by logan-markewich** [comment]
I mean, using NLTK vs a simple regex in TS is probably the main slowdown.

Using NLTK is much more robust (with less false-positive splits).

If you need speedups, you can run multiprocessing using an ingestion pipeline. 
https://docs.llamaindex.ai/en/stable/module_guides/loading/ingestion_pipeline/root.html#parallel-processing

Otherwise, I don't think this will get fixed without removing NLTK from the splitter

**Comment by logan-markewich** [comment]
I don't think this will be fixed without removing NLTK

Yes its faster if you split the document object, but how you do that split really depends on the file being loaded.

What type of file were you testing on?

**Comment by gargn** [comment]
Thanks for the quick response!

Do you have any insight into why TS is so much faster than Python? Is there anything that can be done to improve the speed of the Python implementation?

> I don't think this will be fixed without removing NLTK

Just to clarify - are you suggesting that it is expected behavior that the system is slow with large documents and the recommended approach is to split the document up before generating nodes?

> What type of file were you testing on?

It's a plain text file. I attached it for reference!

[large_testfile.txt](https://github.com/run-llama/llama_index/files/14271403/large_testfile.txt)

**Comment by logan-markewich** [comment]
The only thing that can be done to speed it up for python (besides pre-splitting) is not using nltk -- which tbh I kind of don't think it's worth it, it's a much better sentence splitter than a regex

**Comment by bborn** [comment]
Ran into the same thing. Would it work better to default to use Unstructured as the loader type for `.txt` extensions?

```
file_extractor = {
                ".txt": "UnstructuredReader",
            }

loader = SimpleDirectoryReader(temp_dir, file_extractor=file_extractor)
```

@logan-markewich  does this make sense?

**Comment by logan-markewich** [comment]
@bborn yea that could help (you'll want to instantiate the loader there I think, not just pass the class)

**Comment by bborn** [comment]
@logan-markewich looks like in the LlamaHub package it's set up to just take a string: 

https://github.com/run-llama/llama-hub/blob/main/llama_hub/file/base.py#L11

But the `SimpleDirectoryReader` in llama-index core wants a class: 

https://github.com/run-llama/llama_index/blob/3823389e3f91cab47b72e2cc2814826db9f98e32/llama-index-core/llama_index/core/readers/file/base.py#L37

**Comment by logan-markewich** [comment]
@bborn whatever is in llamaindex now is law , llamahub (the repo anyways) deprecated. Llamahub.ai is also updated to read from the core llama-index repo now

**Comment by preemoDez** [comment]
I think that this [code](https://github.com/run-llama/llama_index/blob/f7b3fee2c273543a6251dbff6cda769b63823179/llama-index-core/llama_index/core/node_parser/text/sentence.py#L191) might be the culprit. I will run more tests to confirm. There may be some other places.

However, this is an $O(n^2)$ algorithm. You can imagine a situation when the split generates a split into 2 parts (long, short). Short could be like 1 token, or something super short. Then you recurse on the long, repeat the scan on the whole text, and get (long, short) split again. This way, you will perform $O(n^2)$ operations. Some time ago I was also testing the random sequence of 25 mln letters and numbers, no spaces. I got a stack overflow, because of this issue. Could you please fix this function to $O(n)$ and maybe remove the recursion?

This would require the code refactoring. It might not be that simple, and depends on the chunking logic, but here is an idea for $O(n)$ algorithm:

```
l = 0, r = 0;
while (r < text.length()) {
  if(r-l > chunkSize) {
    // time to add the new chunk, you need to do that now
    // try to get the best split possible, within the chunk size
    for every splitter sp in order
      if(lastGoodSplit[sp] >= l {
        splits.add(text[l,lastGoodSplit[sp]]
        l = lastGoodSplit[sp] + 1
        foundSplit = true
        break
      }
    // if you didn't find a split, chunk the text by size, as you have to do that anyway
    if(!foundSplit) {
      splits.add(text[l,r-1])
      l = r
    }
  }
  for every splitter sp in order
    if canSplit(sp,r)
      lastGoodSplit[sp] = r
} 

if(l < r) {
  splits.add(text[l,r-1])
}
```

**Comment by preemoDez** [comment]
Ok, I investigated the issue more and found 2 problems. One is with the algo above, but this is a smaller issue in this specific case:

Execution time for split: 12.53 seconds ------> $O(n^2)$ above
Execution time for merge: 0.78 seconds
Execution time for split_text_metadata_aware: 13.31 seconds
Execution time for build_nodes_from_splits: 50.06 seconds ----> ????

When looking further, I noticed that building involves adding the relationship to the source document:

```
relationships={NodeRelationship.SOURCE: ref_doc.as_related_node_info()},
```

and I looked into [as_related_node_info()](https://github.com/run-llama/llama_index/blob/c18b32348583e2ec79500830125103030734b16d/llama-index-core/llama_index/core/schema.py#L346) and noticed that the last line is problematic:
```
hash=self.hash,
```

When I checked the code [here](https://github.com/run-llama/llama_index/blob/c18b32348583e2ec79500830125103030734b16d/llama-index-core/llama_index/core/schema.py#L388), it turned out that the hash is not cached, it's recomputed for the whole 8 MB text for every node. In the case of 10K nodes, this is a huge perf overhead.

Not sure if caching is the right solution, but you could also get that value once before the loop and just pass it.

**Comment by bborn** [comment]
@preemoDez that looks like a good catch, but in our case, we're not using the node parser, so I don't think that's the cause. I'm suspicious of this line:

https://github.com/run-llama/llama-hub/blob/main/llama_hub/file/base.py#L153

When the file extension is `.txt`, no file extractor will match, and the entire file contents will be loaded into a single `Document`. Not sure what the memory implications might be, but in the case of a very large text file (e.g. tens of megabytes), it seems like it could be a problem. 

I ended up adding a text file extractor:

```
file_extractor = {
    ...
    ".txt": TextReader(),
}
loader = SimpleDirectoryReader(temp_dir, file_extractor=file_extractor)
```

And my `TextReader` calls Unstructured's `partition_text` directly:
```
    def load_data(
        self,
        file: Path,
        extra_info: Optional[Dict] = None,
        split_documents: Optional[bool] = False,
    ) -> List[Document]:
        """Parse file locally"""

        elements = partition_text(
            filename=str(file),
        )
```

(Note that if you just pass a `txt` Unstructured's `partition` like the [`UnstructuredReader`](https://github.com/bborn/llama_index/blob/369973f4e8c1d6928149f0904b25473faeadb116/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/base.py#L71) does, it will try to guess the file content type, which could treat your text as JSON or CSV in some cases)

**Comment by preemoDez** [comment]
Hi @bborn, I do not understand what do you mean by `our case`. I pasted the executed Llama Index code, which caused the issue when extracting nodes from the large text file. The original code is at the top:

```
reader = SimpleDirectoryReader(input_files=[filepath])
documents = reader.load_data()
splitter = SentenceSplitter.from_defaults(
    chunk_overlap=32,
    chunk_size=256,
)
llama_nodes = splitter.get_nodes_from_documents(documents=documents)
```

**Comment by bborn** [comment]
@preemoDez sorry, I meant in "my case".

**Comment by preemoDez** [comment]
Ok, let's use this bug for the second issue, I will create a new one for the split algorithm.

**Comment by david1542** [comment]
I'm also experiencing a significant slow performance of the sentence splitter. I'm trying to run it on 6K documents, each one with 10K - 30K tokens.
