### ISSUE TITLE
[Bug]: llamaindex-cli fails to initilize

### ISSUE THREAD

**Issue by GiovanniGatti** [run-llama/llama_index#10716]
### Bug Description

I'm getting this error when trying to run llamaindex-cli (fresh install):

```
(test) $ llamaindex-cli rag --create-llama
Traceback (most recent call last):
  File "[...]/bin/llamaindex-cli", line 8, in <module>
    sys.exit(main())
  File "[...]/lib/python3.10/site-packages/llama_index/core/command_line/command_line.py", line 269, in main
    args.func(args)
  File "[...]/lib/python3.10/site-packages/llama_index/core/command_line/rag.py", line 369, in <lambda>
    instance_generator().handle_cli(**vars(args))
  File "[...]/lib/python3.10/site-packages/llama_index/core/command_line/command_line.py", line 74, in default_rag_cli
    from llama_index.vector_stores.chroma import (
ModuleNotFoundError: No module named 'llama_index.vector_stores'
```

### Version

0.10.3

### Steps to Reproduce

Install latest version of llamaindex with `pip install llama-index chromadb`, then run the cli command.

**Comment by logan-markewich** [comment]
@GiovanniGatti you need to install chromadb as well

`pip install llama-index-vector-stores-chroma`

hidden deps aren't fun -- we are moving the CLI to its own package in the next week or so, so that deps are nicely handled

**Comment by nerdai** [comment]
Hi @GiovanniGatti, are you using a fresh new venv when moving over to v0.10? If llama-index v0.9.xx is installed on your venv, then it will surely cause issues, and perhaps is what's causing this circular import.

I just tried this import statement in a fresh virtualenv where I installed llama-index v0.10.3 and it worked:

```
pyenv virtualenv venv
pyenv activate venv
pip install llama-index
```

While venv is still active, invoking python interpreter (i.e., via `python`)
```
>>> from llama_index.core.prompts.base import PromptTemplate
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nerdai/.pyenv/versions/venv2/lib/python3.11/sit
[nltk_data]     e-packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nerdai/.pyenv/versions/venv2/lib/python3.11/sit
[nltk_data]     e-packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt.zip.
>>>
```

(Please don't mind the nltk data that is downloaded since it recognizes this is a fresh install)
