### ISSUE TITLE
[Question]: node_content is serialized within metadata and hence stored in the database

### ISSUE THREAD

**Issue by kaniosm** [run-llama/llama_index#10967]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

I noticed an additional attribute in the metadata column (node_content), being generated and store together with the metadata.
From what I understand this attribute is used during search for simplicity purposes.
Could this be moved outside the metadata column to avoid storing duplicate data.
We are updating the metadata from our ORM framework, which requires updating the embedded object as well, can the update happen from the store directly without having to delete and regenerate the embedding?

**Comment by logan-markewich** [comment]
What vector store are you using? The `_node_content` field shouldn't be duplicating data (hopefully), most vector stores remove the text from this field if the text is already stored in another field

**Comment by kaniosm** [comment]
Hi Logan,

Thanks for the prompt reply!
We are using PgVector, and in our case the _node_content appears in the metadata_ column in our PG table:

![image](https://github.com/run-llama/llama_index/assets/28901791/affcdc1e-b551-4163-a820-69e11e6b4198)

**Comment by kaniosm** [comment]
From what I understand in the source code, the remove_text flag is used to remove the text field from metadata and not the _node_content.

Just to add some info around this... initially we tried to change the top level attributes in the metadata_ column in PG, which had no effect in our app. We then realized that the same attribute under the _node_content attribute in metadata_ is actually the one considered during retrieval. The top level attributes exists just to hold the data the first time the document is embedded, and those attributes the _node_content gets generated (jsondumps(node_dict)). i.e. node_to_metadata_dict is only called when addind notes.

![image](https://github.com/run-llama/llama_index/assets/28901791/4fc3cb8c-2cc4-4ff7-ab29-b75f4cd74c3c)

**Comment by ramarnat** [comment]
The issue we are seeing with node content being added to the metadata is with relationships. We have a reader that reads a Document, and then a parser that creates the nodes from the document, adding the source node from the reader into the the node.relationships as `SOURCE`. The issue with that is that when the metadata gets sent to the vector store, it is including the full content of the original source node including the text of that source node.

**Comment by ramarnat** [comment]
Hmm, maybe we need to create RelatedNodeInfo instead of the actual source Node instead?

**Comment by ramarnat** [comment]
Even with RelatedNodeInfo, the node_content can get large if there are many related nodes (parent-child) for example. 

Do related nodes need to be fully encapsulated in node content? Could rated nodes just be a reference with the node id and lazily retrieved?

The other option is to have some sort of EXCLUDE keys in the as_related_node method or reference only setting that only returns the id. I don't know what sort of downstream need is required of related nodes' metadata.

**Comment by mlevtov** [comment]
We are seeing the same issue. 
We are using the SentenceWindowNodeParser with the MetadataReplacementPostProcessor. The `_node_content` field of each node contains the `window` and `original_text` of the nodes (which is a duplicate of those nodes fields), but also the `window` and `original_text` of the related nodes. Is the data from the related nodes used?

The problem is that the `_node_content` field ends up being about 10,000-20,000 characters for each node in our case, massively increasing our vector store resource requirement and cost.

Are there any workarounds to reduce this?

**Comment by AceHomard** [comment]
Hi everyone,
Thanks for the discussion in this thread, it helped clarify a few things, but I’d like to share my specific case since I’m encountering the same issue.

### 🔧 Context

I'm using `LlamaIndex` to process and index documents into Qdrant, with the following setup:

```python
VectorStoreIndex.from_documents(
    documents,
    vector_store=QdrantVectorStore(
        client=qdrant_client,
        collection_name="my_collection",
        content_payload_key="text",
        metadata_payload_key=None,
    )
)
```

### ✅ Expected behavior

I expected the payload of each Qdrant point to look like this:

```json
{
  "text": "The raw content of the document...",
  "page_label": "1",
  "file_name": "document.pdf",
  "document_id": "abc-123"
}
```

This format aligns with the Qdrant + LlamaIndex documentation and allows proper use of `content_payload_key="text"` for similarity search.

### ❌ Actual behavior

Instead, I get a payload like this:

```json
{
  "page_label": "1",
  "file_name": "document.pdf",
  "document_id": "abc-123",
  "_node_content": "{\"id_\": \"...\", \"text\": \"The raw document content...\", \"metadata\": {\"...\": \"...\"}, ...}",
  "_node_type": "TextNode"
}
```

Key issues:

* The `text` content is **not available at the root level** of the payload, it’s embedded inside `_node_content` as a serialized JSON string.
* This makes the `content_payload_key="text"` ineffective, since there is no `text` key at the root.
* The `_node_content` field is large, redundant, and was **not part of my original `Document` objects**. It seems to be added by LlamaIndex during serialization.

### 🎯 Goal

I'd like to:

1. Avoid storing `_node_content` altogether (to reduce payload size and redundancy).
2. Ensure that the `text` key is present at the root of the payload, as expected by Qdrant and LlamaIndex.

### 🙋‍♂️ Question

Is this `_node_content` behavior intentional, or is there a way to disable/customize it?
If there’s a preferred solution (or if a PR would be welcome), I’d be happy to contribute one.

Thanks again!

@AceHomard

**Comment by spreeni** [comment]
I also find this very unsatisfying and inefficient in cases of larger metadata, in my case with the OpenSearch integration. Would be nice to solve it more through references than straight duplication.
