### ISSUE TITLE
[Bug]: Unable to use SelfDiscoverPack 

### ISSUE THREAD

**Issue by orhansonmeztr** [run-llama/llama_index#11014]
### Bug Description

When I try to use SelfDiscoverPack via download_llama_pack, I'm getting ValueError: Failed to find python package for class SelfDiscoverPack.
How can I use SelfDiscoverPack?

### Version

v0.10.7

### Steps to Reproduce

```
pip install llama_index==0.10.7

import os
os.environ["OPENAI_API_KEY"] = "my-api-key"
from llama_index.llms.openai import OpenAI
llm = OpenAI("gpt-3.5-turbo")

#The code below doesn't work. It gives ValueError: Failed to find python package for class SelfDiscoverPack.
from llama_index.core.llama_pack import download_llama_pack
SelfDiscoverPack = download_llama_pack("SelfDiscoverPack", "./self_discover_pack")
self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)

#The code below doesn't work either. It gives ModuleNotFoundError: No module named 'llama_index.packs'.
#from llama_index.packs.self_discover import SelfDiscoverPack
#self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)
```

### Relevant Logs/Tracbacks

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-5-63247be966cb> in <cell line: 3>()
      1 from llama_index.core.llama_pack import download_llama_pack
      2 
----> 3 SelfDiscoverPack = download_llama_pack("SelfDiscoverPack", "./self_discover_pack")
      4 
      5 self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)

/usr/local/lib/python3.10/dist-packages/llama_index/core/llama_pack/download.py in download_llama_pack(llama_pack_class, download_dir, llama_pack_url, refresh_cache)
     45         new_install_parent = new_import_parent.replace(".", "-").replace("_", "-")
     46     else:
---> 47         raise ValueError(f"Failed to find python package for class {llama_pack_class}")
     48 
     49     if not download_dir:

ValueError: Failed to find python package for class SelfDiscoverPack
```

**Comment by ravi03071991** [comment]
@orhansonmeztr following code does work for me on llama-index==0.10.7 version.
```python
from llama_index.packs.self_discover import SelfDiscoverPack
self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)
```

**Comment by orhansonmeztr** [comment]
@ravi03071991 
I'm trying to run the code you wrote, but I couldn't succeed neither in Colab nor locally. 
Could you watch the [screen recording video](https://drive.google.com/file/d/1faahrdTreZKJ_KJThcmwUzX-iSqn6j69/view?usp=sharing), please?

**Comment by nerdai** [comment]
Hi @orhansonmeztr, sorry that you're running into some troubles with downloading and installing this pack.

There are two ways to install llama-packs as mentioned in [this](https://github.com/run-llama/llama_index/tree/main/llama-index-packs#llamapacks-) README:

1. via `pip install llama-index-packs-<name-of-pack>` -> use this if you just plan to use the pack and not customize it
2. via `download_llama_pack` -> use this if you do plan to customize it, since it downloads the source code in specified directory and subsequently installs it.

My recommendation is always 1. (again unless you plan to customize the pack). There is an unfortunate reliance on `mappings.json` using 2. at current moment, that I'd like to de-couple for obvious reasons such as the `mappings.json` has to be manually updated at this point. Will submit a fix for that soon.

To get you going in the meantime, the reason `from llama_index.packs.self_discover import SelfDiscoverPack` this doesn't work for you at current moment is because this is used after doing 1. above. In other words, you need to install the python package that contains `SelfDiscoverPack`.

```sh
pip install llama-index-packs-self-discover
```

After that, you should be able to use your import statement (and rest of code)

```
from llama_index.packs.self_discover import SelfDiscoverPack
self_discover_pack = SelfDiscoverPack(verbose=True, llm=llm)
```

**Comment by nerdai** [comment]
@logan-markewich can we update the `mappings.json` as at least a temporary fix for this so that `download_llama_pack` will work for this class and others that are currently not listed in this file? Trying to think of how we can do this better at the same time.

**Comment by logan-markewich** [comment]
@nerdai definitely we can update the mappings.json
