### ISSUE TITLE
Can i rely completly on index,vector store index created by llmaindex and i persist them And i retrive on top of these index . Instead of using any Vector database 

### ISSUE THREAD

**Issue by anantwag19** [run-llama/llama_index#11079]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

instead of using any vector database to store and retrieve during  querying . 
Can i use the default vector index store created by llmaindex which i can persist on Disk and then top if it i can do all retrieval  needed  .
Can you give me Prons and Cons  for using the deffault vector index store created by llmaindex over Storing vector index in standard Vector Database ?

**Comment by anantwag19** [comment]
Vector_store index but we can keep updating right , If we are  taking care of sessions during ingestion .
For example :  one file ---->parsing -->chunk--> embedding--->Persist on Disk(Session closed)
                        second file --->parsing -->chunk--> embedding--->Persist on Disk(Session closed)

So end of the day my vector store never overwritten and infact it grew for every document .

**Comment by logan-markewich** [comment]
The default vector store is very simple -- all in memory, retrieval is done by comparing the query vector to every node vector and calculating cosine similarity.

For small indexes this is ok.

For larger indexes, other DBs like qdrant, weaviate, etc. use more optimized algorithms that are faster and use less memory for larger datasets.

If the simple vector store starts taking up too much memory or is slowing down, its probably time to switch

**Comment by mirakamali** [comment]
Hello, thank you for your answers. I have a question. I am using VectorStoreIndex.from_documents , also tried the ones with async=True, however when I am trying to scale my app, the time to create the embeddings are adding up instead of being well parallelized. I am calling them using async fast api and also run the function in a threadpool executor.  Although I am saving the embeddings in memory, the memory is not full- In other words, if i have 2 users calling the VectorStoreIndex, one is waiting for the user. is it normal?
Also I have another question, does this function have a retry mechanism in  case there was an error when creating embeddings (such as 429 rate limit). If yes, where can i find this info and parameters. I tried to go through the function of VectorStoreIndex but couldn't find anything.
Thanks in advance. I hope you can help me.

**Comment by marabian** [comment]
I was wondering if you found a solution to the problem of running `VectorStoreIndex.from_documents` with multiple workers via async? I have the same problem with it being slow. @mirakamali
