### ISSUE TITLE
[Feature Request]: How to set seeds for RAG results?

### ISSUE THREAD

**Issue by HelloWorldLTY** [run-llama/llama_index#11257]
### Feature Description

Hi, I wonder if there are any keywords to set seeds for the rag process. I have tried torch.manual_seed(seed). Does this work? Thanks.

### Reason

I think this feature is important.

### Value of Feature

I think this feature is important.

**Comment by ravi03071991** [comment]
@HelloWorldLTY have you tried out the seed parameter that is present in OpenAI and MistralAI LLMs? 

`seed` parameter in OpenAI - https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed
`random_seed` parameter in MistralAI - https://docs.mistral.ai/api/#operation/createChatCompletion .

The retrieval part is always consistent for a query because embeddings don't change so the generation part can be made consistent with the seed parameter.

**Comment by HelloWorldLTY** [comment]
Thanks, I will try. I think it will be better if we have a general API here. And I think for example, the sequence of chunks can also affect results, thus maybe another seed for the documents is also interesting.

**Comment by ravi03071991** [comment]
@HelloWorldLTY as said the retrieval part is always consistent for a query because embeddings don't change and so the sequence of chunks would be consistent for an embedding model and query.
