### ISSUE TITLE
[Bug]: "contain" is implemented instead of "in" 

### ISSUE THREAD

**Issue by qiisziilbash** [run-llama/llama_index#11406]
### Bug Description

see latest comment on this PR https://github.com/run-llama/llama_index/pull/10547

### Version

latest

### Steps to Reproduce

Use the in filter

**Comment by qiisziilbash** [comment]
I might be missing something but I can open a PR if it is confirmed

**Comment by logan-markewich** [comment]
@qiisziilbash since pgvector stores metadata as a JSON blob, doesn't contain make sense? Isn't `IN` specific for lists? I might be wrong though, not a pgvector expert :)

**Comment by juleskuehn** [comment]
Absolutely, the implementation in LlamaIndex is backwards.

@qiisziilbash I don't see how your code will succeed since `to_postgres_operator` will return `@>`, which is "contains" (see https://www.postgresql.org/docs/current/functions-json.html).

For minimal changes to the code, the `MetadataFilter` could be expressed in the calling code like this:
```python
MetadataFilter(key="author", value="('Jane', 'John')")
```

Then in PGVectorStore class, these 2 changes:
```python
def _to_postgres_operator(self, operator: FilterOperator) -> str:
    ...
    elif operator == FilterOperator.IN:
        return "IN"
    ...
    
def _recursively_apply_filters(self, filters: List[MetadataFilters]) -> Any:
    ...
    sqlalchemy.text(
        f"metadata_->>'{filter_.key}' "
        f"{self._to_postgres_operator(filter_.operator)} "
        (
            f"{filter_.value}"
            if filter_.operator == FilterOperator.IN
            else f"'{filter_.value}'"
        )
    )
    ...
```

See https://github.com/juleskuehn/llama_index/commit/6e610308c69189ba895cdf127ad206cad50e7474

**Comment by qiisziilbash** [comment]
yeah for sure; close this when ur PR merges :) 
I was going to PR the same thing
