### ISSUE TITLE
[Question]: Feedback on version bump to v0.10

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#11467]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi @logan-markewich @nerdai. I finally migrated to v0.10. It was pretty easy to do especially thanks to the CLI tool you worked so hard on. Thanks a lot. The library is much more modular and its really easy to work with the new install commands: pip install llama-indes-llms-cohere, llama-index-vector-stores-pinecone etc... 

I have a pretty complex system and nothing has broken so far, so thanks for the work.

I do have one question though, why did you guys decide to deprecate the service_context? It was a really convenient abstraction for a user since they didn't need to know what every single module required and could just pass in a specific service context that they curated. What motivated this change?

**Comment by logan-markewich** [comment]
@gich2009 thank you for the kind words! Glad you appreciate the update (and also glad it was a smooth upgrade!)

the service context was a complex abstraction -- it had to be passed down to components (which wasn't always happening, leading to bugs), and it forced users to initialize things they weren't even using ("Why does `VectorStoreIndex.from_documents()` force me to initialize an LLM?" and things like that were common). (Initializing things not being used also eats a lot of memory)

It was also very verbose to configure, especially when only changing one or two things.

Instead, now we have
a) proper global settings (don't like the openai defaults? Change them in 3 short lines). They are lazily initialized to save memory.
b) now, its very clear what abstractions use which components (at the cost of bundling them all as previously)
c) its also clear when you are overriding the defaults in Settings

I hope that is a satisfactory explanation :)

Do note that I am currently working on a huge update to our API reference docs (docstrings and defaults documented for everything!), so that will also help ease this migration as well I think

**Comment by gich2009** [comment]
@logan-markewich, thanks for the explanation. 

I understand the need for this now, and why you opted for clarity over bundled initialization.

There are 3 problems. Two of which llama-index currently solves:
1. The Settings is a solution for global configuration 
2. For single module configuration, you can pass in the specific components that are required by each abstraction


3. What about when you want some settings to apply to 10 modules and some settings to apply to 5 modules and others to 8 modules etc... Then it becomes pretty cumbersome because now you have to pass in the same settings to 10 different things that would probably need to change together. The service context could potentially address this need if it is refactored in such a way that it only uses the components required when passed into an abstraction. 

Is there a way to do this with Settings?

**Comment by nerdai** [comment]
Thanks @gich2009 for your feedback!

**Comment by logan-markewich** [comment]
@gich2009 no way to do that with settings (unless this code is running in a separate processes/programs)

Probably I would just define some variables in the parent scope and pass them into each module, this way you only have to modify a single variable to update all modules using that variable

**Comment by gich2009** [comment]
Fair enough, I'll see how best to do this at my application's level.

Anyways, great work again from the team. @nerdai, @logan-markewich and @ravi03071991. It's super easy working with llama-index in general, so kudos for your commitment.
