### ISSUE TITLE
[Question]: A question about testing new contributed packages

### ISSUE THREAD

**Issue by DJC-GO-SOLO** [run-llama/llama_index#11498]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to rewrite the searchain framework using llama_index. Currently I have completed the source code and am preparing to write test cases. I found that the test cases for other similar packages (such as self-rag) seem to have classes imported directly from the official llama_index package (such as SelfRAGPack). However, I did not submit a pull request, so the searchain framework I wrote must not be included in the official llama_index package. This seems to form a logical closed loop?

![image](https://github.com/run-llama/llama_index/assets/85006613/eef9f9ff-5115-4f87-a8a9-4250268d6d4d)
（Test case in self-rag, it worked! ! !）

![image](https://github.com/run-llama/llama_index/assets/85006613/a1b6feb1-4d08-4e8e-92cb-bf8f88c10f6c)
(When I want to write test cases about searchain locally, I fail...)

Maybe this is a very stupid question, please forgive me for being a newbie.

**Comment by logan-markewich** [comment]
Instead of testing download_llama_pack, just assume that will work.

Rather, you can just `pip install -e <path to root of my package>` to install the package (the path should point to the folder where the pyproject.toml is for your pack), and from there you can import it
`from llama_index.packs.SearChainPack import SearChainPack` or something like that

Then, you can continue on with testing
