### ISSUE TITLE
HELP!!!!!!!!!! Can anyone help me in understanding how knowledge graph works internally in llama index?

### ISSUE THREAD

**Issue by vishnu9000** [run-llama/llama_index#11600]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am having trouble understanding knowledge graph working in llama index. I understood few parts but I am not having clear understanding of other sections. Following are the things I understood:

1. Why knowledge graph is needed and how to construct it using llm
2. How to use existing knowledge graph like neo4j or nebula.
3.  How user query is converted to cypher query for getting answer from KG.

What i don't understand:

1. I have seen two way to construct answer from KG. First is direct cypher query creation, next is subgraph creation. In both case I have seen we are only retrieving the triplets like source relationship and target. But many cases without actual context from where this has been retrieved only with source-relationship-target triplet we cannot give accurate answer. So are we storing the chunk from where this triplet was created? If yes are we using that also to generate answers? If yes wouldn't that overflow our context window? and how will it be different from normal vector search?
2. I have seen index query engine showing answers for question which are not in graph, so how to set prompt here?

**Comment by vishnu9000** [comment]
@dosubot Understood. So you are not storing the chunk where the triplet has been extracted. If that the case just relying on the triplets will it be complete answer? If the context from where this was retrieved is not included. Also let say if an entity in question has more than 100 relations, isn't it a leap of faith to put all its relation in context?

What does graph_store_query_depth and similarity_top_k do?

Also my second question is I saw a section in your document which shows how to manually add triplets in graph. Here you are also inserting the text chunk. Why is that?

**Comment by logan-markewich** [comment]
@vishnu9000 `isn't it a leap of faith to put all its relation in context` -- its fine, since a response synthesizer is used which handles context limits

`graph_store_query_depth and similarity_top_k do` -- the first one modifies how "deep" to retrieve (If I retrieve a triplet, do I retrieve its neighbors? Neighbors of neighbors? etc.). Similarity_top_k is used when you constructed the triplets with embeddings. 

`Here you are also inserting the text chunk. Why is that?` -- triplets are mapped to a text chunk where the triplet was extracted from. This is what `include_text` parameter does (i.e. do I send a the chunks where matching triplets are found to the LLM, or just the triplets alone)

**Comment by logan-markewich** [comment]
I really recommend just reading the source code for a deeper understanding here

**Comment by noviljohnson** [comment]
What happens to the Chunks that we pass to the KG creation function in Llamaindex (knowledgegraphindex() or ...)
How the chunks will be stored, how the retrieval happens 
what are the 4or5 json files that are getting created if we store the using simple graph store
