### ISSUE TITLE
[Bug]: SimpleVectorStore doesn't fit with Ingestion Pipeline

### ISSUE THREAD

**Issue by ret2libc** [run-llama/llama_index#11688]
### Bug Description

Similarly to https://github.com/run-llama/llama_index/issues/11397 (fixed with https://github.com/run-llama/llama_index/pull/11432/files), also `SimpleVectorStore` does not implement the `BasePydanticVectorStore` and when used as a `vector_store` within an `IngestionPipeline` it results in an error:

```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for IngestionPipeline
vector_store
  value is not a valid dict (type=type_error.dict)
```

### Version

0.10.15

### Steps to Reproduce

```python
        vector_store = SimpleVectorStore()
        pipeline = IngestionPipeline(
            transformations=[
                embed_llm,
            ],
            vector_store=vector_store,
        )
        pipeline.run(documents=documents, show_progress=True, num_workers=4)
```

### Relevant Logs/Tracbacks

```shell
pydantic.v1.error_wrappers.ValidationError: 1 validation error for IngestionPipeline
vector_store
  value is not a valid dict (type=type_error.dict)
```

**Comment by logan-markewich** [comment]
@ret2libc SimpleVectorStore does not store text, and so cannot actually be used with the ingestion pipeline in this way. Since it doesn't store text, it requires a complete docstore and index store to function. This is not something that will be changed anytime soon.


You can run the pipeline and then build your index with the resulting nodes

```
nodes = pipeline.run(documents=documents)

index = VectorStoreIndex(nodes=nodes)
```
