### ISSUE TITLE
[Question]: How to convert a query engine into a chat engine?

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#11782]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm following this tutorial to implement a few experiments on RAPTOR https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb. However, I encounter a blocker when integrating to my existing code base. The tutorial uses a query

**Comment by logan-markewich** [comment]
You can use it in an agent or condense question chat engine
https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent_with_query_engine.html#openai-agent-with-query-engine-tools

If you wanted to use it in a context or condense plus context chat engine, you'd have to wrap it in a custom retriever (those two only work with retrievers)

Don't be afraid to import that actual classes instead of relying in index.as_chat_engine 💪🏻
