### ISSUE TITLE
[Question]: instrumentation + retrieved node with score event

### ISSUE THREAD

**Issue by mikelonestone** [run-llama/llama_index#12047]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm looking for a way to use new instrumentation module to track queries retrieved nodes + score (I'm currently using a custom node processor).
I've seen there is a RetrievalEndEvent but I don't have information I'm looking for there, is there a way of doing that or should I stick to my current implementation ?

**Comment by nerdai** [comment]
Cool @mikelonestone! In general, we need to expand the coverage of `instrumentation` throughout our library, by:

- adding sensible payloads to existing `Event`
- adding new `Event`
- firing `Event` with dispatcher
- tracing function executions with `Span`

We see the above happening as dictated by the needs of our users mostly, and your present one prime example.

I believe for your case, if I'm understanding correctly, we would need to add the relevant payload (i.e Fields) in the appropriate `Event` classes.

```python
from llama_index.core.instrumentation.events.base import BaseEvent


class RetrievalStartEvent(BaseEvent):
    query: str  # ADD

    @classmethod
    def class_name(cls):
        """Class name."""
        return "RetrievalStartEvent"


class RetrievalEndEvent(BaseEvent):
    query: str   # ADD
    retrieved_nodes: Dict[str, Any]  # ADD (or could maybe NodeWithScore)

    @classmethod
    def class_name(cls):
        """Class name."""
        return "RetrievalEndEvent"
```

We have to be somewhat mindful of the data types on the payloads as they all might not work. After having the events like above, then in order to catch these events and handle them with your custom logic you need to:

1. Define your custom `EventHandler`
2. Attach it to the root `Dispatcher`

```python
from llama_index.core.instrumentation.event_handlers.base import BaseEventHandler
from llama_index.core.instrumentation.events.retrieval import RetrievalStartEvent, RetrievalEndEvent

class MyCustomEventHandler(BaseEventHandler):
     def handle(event):
          # add your custom logic here
          if isintance(event, RetrievalEndEvent):
                  ...


# to attach to root dispatcher
import llama_index.core.instrumentation as instrument

dispatcher = instrument.get_dispatcher()  # with no "name" param supplied, it will get the root dispatcher
event_handler = MyCustomEventHandler()

dispatcher.add_event_handler(event_handler)
```
```
