### ISSUE TITLE
[Question]: How to use a QueryEngineTool with a QueryPipeline DAG?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#12067]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using a QueryPipeline built with the low-level DAG API.  I want to use QueryEngineTools to implement multi-document queries, but the constructor seems to require a query engine, which is not used in the QueryPipeline.  Is there still a way to use a QueryEngineTool with a QueryPipeine?  If not, is there an alternative?

**Comment by logan-markewich** [comment]
I think you can wrap it in a custom query engine
(Also linking in my beta docs, because that's what I had open)
https://docs.llamaindex.ai/en/logan-docs_3.0/examples/query_engine/custom_query_engine/

The API is quite new though, it could probably use a better way to do this. The main issue is a query engine has one input (the query), while the query pipeline can have arbitrary inputs
