### ISSUE TITLE
multi gpu support when loading llm for rag

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#12080]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

    llm = HuggingFaceLLM(
        context_window = 8000,
        max_new_tokens=512,
        generate_kwargs={"temperature": 0.1, "do_sample": True},
        system_prompt=system_prompt,
        query_wrapper_prompt=query_wrapper_prompt,
        tokenizer_name="meta-llama/Llama-2-13b-chat-hf",
        model_name="meta-llama/Llama-2-13b-chat-hf",
        device_map="cuda:0",
        tokenizer_kwargs={"max_length": 8000},
        model_kwargs={"torch_dtype": torch.float16, "load_in_4bit": True}
    )
if i use auto for device_map, the code breaks, is it possible to use two gpus for model loading for doing RAG?

**Comment by JINO-ROHIT** [comment]
is there any other framework that support multi gpu for open source models?

**Comment by logan-markewich** [comment]
@JINO-ROHIT multi-gpu is a little complicated. It's not implemented.

I would recommend implementing your own custom LLM class to run the model how you want
(linking from a beta docs page, because that's what I have open right now lol, this page is also in the normal docs)
https://docs.llamaindex.ai/en/logan-docs_3.0/module_guides/models/llms/usage_custom/#example-using-a-custom-llm-model-advanced
