### ISSUE TITLE
[Documentation]: Repair V9 Documentation Pages

### ISSUE THREAD

**Issue by CHesketh76** [run-llama/llama_index#12329]
### Documentation Issue Description

Any and all v9 documentation has been removed and deleted. 
I get it that v10 is out but I am sure there are others out there, like me, where the v10 version has to go through year long review process and v9 is the only option.

### Documentation Link

https://docs.llamaindex.ai/en/v0.9.48/examples/embeddings/Langchain/

**Comment by logan-markewich** [comment]
@CHesketh76 the docs are there, but since it uses a different docs build system, the links are slightly different 
https://docs.llamaindex.ai/en/v0.9.48/examples/embeddings/Langchain.html

So you can't just change the version and have it work. I suggest using the homepage and going from there, using search
https://docs.llamaindex.ai/en/v0.9.48
