### ISSUE TITLE
SQLDatabase.from_uri connection to PostgreSQL

### ISSUE THREAD

**Issue by maby200** [run-llama/llama_index#1254]
Hello everyone,

I am trying to connect to postgresql using:
```python
...
db = SQLDatabase.from_uri('postgresql+psycopg2://user:password@RemoteIP:1234/postgres')
...
```
_Bear in mind that user, password, RemoteIP(like: 12.123.12.123) and 1234 (the port)_ are dummy data here.
I also installed langchain and psycopg2 on my python environment.

But get two errors:

```bash
...
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "RemoteIP", port 1234 failed: FATAL:  password authentication failed for user "user"

The above exception was the direct cause of the following exception:

...

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "RemoteIP", port 1234 failed: FATAL:  password authentication failed for user "user"
```

I was procedding just as specified [in the LangChain documentation](https://python.langchain.com/en/latest/modules/chains/examples/sqlite.html) and [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/20/core/engines.html#postgresql) but still getting same error.

I hope you can help me please.

**Comment by Noah-Yasarturk** [comment]
Hi there! 
Are we able to confirm a connection with just plain-old SQLAlchemy?
```
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://user:password@RemoteIP:1234/postgres')
```

That should tell you if the issue is with the SQLDatabaseWrapper Llama Index uses from LangChain, or if the issue is with connection details such as:
- user/pw combo incorrect
- hostname incorrect
- port incorrect
- credentials are correct, but your machine can't talk to the Postgres instance due to network rules

More details: 
- Helpful guide: https://www.geeksforgeeks.org/connecting-postgresql-with-sqlalchemy-in-python/
- Official docs - see box for ""Transaction Isolation Level": https://docs.sqlalchemy.org/en/20/dialects/postgresql.html

If you can't connect via the above, the issue is not with Llama Index but with your SQLAlchemy connection
