### ISSUE TITLE
[Question]: ReActAgent doesn't follow system prompt

### ISSUE THREAD

**Issue by DrRaja** [run-llama/llama_index#12810]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to create a ReActAgent and providing a "system_prompt" to it as follows:

```
system_prompt = f"You're an intelligent assistant. Your name is Jarvis."

agent = ReActAgent.from_tools(
	[multiply_tool, add_tool], 
	llm=llm, 
	verbose=True, 
	memory=memory,
	system_prompt=(system_prompt))
```

When I run this code, and ask the agent its name, it returns a default answer; "My name is Assistant". 

What am I doing wrong here?

**Comment by logan-markewich** [comment]
@DrRaja there is no easy system prompt override for the react agent, since the system prompt contains all of the react instructions 

You can provide extra context
https://docs.llamaindex.ai/en/stable/examples/agent/react_agent_with_query_engine/?h=react+context#setup-react-agent

Or you can modify the entire prompt
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern/?h=get_prompts#updating-prompts
