### ISSUE TITLE
[Question]: Is it possible integrate langchain ConversationBufferMemory ?

### ISSUE THREAD

**Issue by sura2k** [run-llama/llama_index#12845]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it possible to integrate langchain `ConversationBufferMemory` with llama-index chat engine?
I'm checking on this because current llama-index `ChatMemoryBuffer` is not sufficient.

**Comment by sura2k** [comment]
@logan-markewich sorry for late reply. I'm actually having a requirement to use something similar to  `ConversationSummaryMemory`

**Comment by shadyelgewily-slimstock** [comment]
We would also like something along the lines of ConversationSummaryBufferMemory to be implemented in LlamaIndex. The reason is that for our use case, we want to keep latency and costs down for our end users. Using the full history up to the context length increases costs and latency. Limiting the memory to the last X messages works, but is suboptimal. We would like older messages < X to be summarized, then appended by the full text of the last X messages.

@logan-markewich I can contribute to this if you are okay with putting this on the roadmap.

**Comment by logan-markewich** [comment]
Yea go for it
