### ISSUE TITLE
[Bug]: Can not download PaulGrahamEssayDataset

### ISSUE THREAD

**Issue by afalf** [run-llama/llama_index#12915]
### Bug Description

Can not download the PaulGrahamEssayDataset. Meet the connection timeout error, and I also can not visit the llamdahub libary url: https://raw.githubusercontent.com/nerdai/llama-hub/datasets/llama_hub/llama_datasets/library.json

### Version

llama-index-0.10.30

### Steps to Reproduce

```
from llama_index.core.llama_dataset import download_llama_dataset
  
# download and install dependencies
rag_dataset, documents = download_llama_dataset(
    "PaulGrahamEssayDataset", "./paul_graham"
)
```

**Comment by nerdai** [comment]
@afalf which version of llama-index are you using? I just tried on llama-index v0.10.31 and it works.

Also, the think you provided points to my personal `repo` which I think was mistakenly (but has since been corrected) used in our codebase. The correct link is provided below:

https://raw.githubusercontent.com/run-llama/llama-hub/main/llama_hub/llama_datasets/library.json
