### ISSUE TITLE
[Question]: Currently a way to create a ChatEngine from a QueryPipeline?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#13037]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

You can create a QueryEngine for a QueryPipeline using CustomQueryEngine.  Is there currently a way to create a ChatEngine for a QueryPipeline?  If not, what about a way to convert a QueryEngine into a ChatEngine?

**Comment by brycecf** [comment]
@dosu The answer relates to a `BaseIndex` which isn't necessarily part of a QueryPipeline.  The answer is irrelevant.  Try again.

**Comment by logan-markewich** [comment]
@brycecf there isn't -- since a query pipeline can be anything (a retriever, a full RAG engine with response synthesis, some other LLM operation, something random) There's no direct way

 But you could
- create a custom query engine for use as a QueryEngineTool in an agent
- create a custom retriever for context/condense+context chat engine
- create a FunctionTool that wraps your pipeline to use in an agent

**Comment by logan-markewich** [comment]
You can even build a chat engine from scratch using your query pipeline (this is basically the context chat engine from scratch)
https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline_memory/?h=query+pipeline

**Comment by brycecf** [comment]
Perfect!  Thank you @logan-markewich
