### ISSUE TITLE
[Question]: Using llama.cpp serve hosted model

### ISSUE THREAD

**Issue by JulianOestreich90** [run-llama/llama_index#13107]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using llama.cpp http server to serve a model with a docker container:
`docker run -d -p ipadress:8080:8080 -v ~/models:/models --gpus all ghcr.io/ggerganov/llama.cpp:server-cuda -m models/mistral-7b-instruct-v0.2.Q4_0.gguf -c 32000 --host 0.0.0.0 --port 8080 --n-gpu-layers 99`

I can talk with the model via curl, e.g.:
```
curl --request POST \                        
    --url http://ipadress:8080/completion \
    --header "Content-Type: application/json" \
    --data '{"prompt": "Building a website can be done in 10 simple steps:","n_predict": 128}'
```

And it returns a response.

However integrating it into llama index does't seem so easy. I tried these two options:
```
import os
from llama_index.llms.openllm import OpenLLMAPI

os.environ["OPENLLM_ENDPOINT"] = "http://ipadress:8080"  # replace with your server address
remote_llm = OpenLLMAPI()

response = remote_llm.complete("Hello World!")
print(str(response))

##########################################################

from llama_index.llms.openai_like import OpenAILike

llm = OpenAILike(api_base="http://ipadress:8080")

response = llm.complete("Hello World!")
print(str(response))
```

The OpenLLMAPI Options errors with `AttributeError: 'HTTPStatusError' object has no attribute 'message'
` and the OpenAILike class also gives connection errors.

What can i do to connect properly to a self hosted remote llm?

**Comment by JulianOestreich90** [comment]
@dosu why should i install `llama-cpp-python` on my server? Does that mean llama index can not handle the API spawned by the llama.cpp http server? It is supposed to be an OpenAI compatible API as well.

**Comment by RussellLuo** [comment]
Hi @JulianOestreich90, in addition to the API you provided, llama.cpp also supports [OpenAI-compatible Chat Completions API](https://github.com/ggerganov/llama.cpp/tree/master/examples/server) (search `POST /v1/chat/completions`). If you use that API, I guess [OpenAI](https://docs.llamaindex.ai/en/stable/examples/llm/openai/) should suffice.

**Comment by jggc** [comment]
Thanks for the suggestion of OpenAI, it did work for me although I've had to mess with the parameters a bit. I ended up with : 


```python
llm = OpenAI(api_key="somestring", api_base="http://192.168.12.132:3300")
```

Leaving the API Key empty breaks it at the moment, it is trying to do authentication with an invalid query.

See this girst for my full RAG script using a single RTX 3070 running llama 8B served with llama.cpp server. I've had to put the embeddings model on CPU since my GPU does not have enough memory.

It's quite satisfying to watch. I randomly picked a few wikipedia articles about giraffes and related concepts for my test, I put the result in as a gist comment.

https://gist.github.com/jggc/5ba572a4753bc851e6d33d07e82b39f4
