### ISSUE TITLE
[Question]:  if Simple Vector Store  has no capacity setting

### ISSUE THREAD

**Issue by waveBoom** [run-llama/llama_index#13144]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to know if  ''Simple Vector Store''  has no capacity setting, that is, it will grow infinitely with the project (or it is only designed for experimentation or testing)

**Comment by logan-markewich** [comment]
The "capacity" is the amount of memory you have, since all the vectors are stored in memory

It's really only meant to get people quickly started or work with smaller amounts of data. Actual use-cases that have larger data requirements etc. should use a vector index integration (qdrant, chroma, weaviate, etc.)

**Comment by waveBoom** [comment]
> The "capacity" is the amount of memory you have, since all the vectors are stored in memory
> 
> It's really only meant to get people quickly started or work with smaller amounts of data. Actual use-cases that have larger data requirements etc. should use a vector index integration (qdrant, chroma, weaviate, etc.)

i get it , thanks
