### ISSUE TITLE
[Question]: Document class relationship property

### ISSUE THREAD

**Issue by NicoMigenda** [run-llama/llama_index#13554]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, 

I got the following question/problem: 
I loaded multiple files using SimpleDirectoryReader. Now i have a list of "Documents" each containing text and metadata. Now I would like to add relationships between these text chunks, so that each chunk has a relationship to all other chunks. The only information I could find was:
_relationships - a dictionary containing relationships to other Documents/Nodes._ (https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/)
Digging through the code I found a NodeRelationship class that contains 5 entries: Source, Previous, Next, Parent, Child. 
Should I formate that dict in that way? What is a parent or a child of a text chunk? 

I would be very thankful for a minimal example.

Kind regards,
Nico

**Comment by NicoMigenda** [comment]
@duso
I wonder how to directly achieve this with SimpleDirectoryReader and SimpleDirectoryReader.load_data(), as this function directly returns a list of Class:Document elements (each containing a chunk) that have an empty relationship property. Is there some function that directly calculates the relationships between each Document element within a list?

**Comment by logan-markewich** [comment]
@NicoMigenda simple directory reader will not initialize any relationships. I believe only the node parsers/text splitters will set the source, prev, and next relationships

Otherwise, its up to you to set these.

The page here has the code samples
https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_nodes/?h=customizing

(you can set relationships on documents and nodes, its the same either way, but the above operates on nodes)
