### ISSUE TITLE
[Question]: PGVectorStore: how to implement text search on metadata?

### ISSUE THREAD

**Issue by coffepowered** [run-llama/llama_index#13743]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I know that the PGVectorStore supports both text embedding and full text search and that they can be combined using a fusion retriever to achieve any flavour of hybrid search one may be interested in.

I see that apache lucene and other engines however support combination of embedding retrieval and full text search on any field (metadata) one is willing to index.

For instance: let's suppose one wants to do embedding search on the node + full text search on its "title" metadata.
Do you think this is achievable ATM? If not, what would be the best pattern to implement this? 

Perhaps subclassing the PGVectorStore+creating a custom retriever?

Thanks in advance

P.S. tagging @juleskuehn  - as I feel he may be expert on this :)

**Comment by juleskuehn** [comment]
Thanks for tagging me. I'm looking into this myself right now also.

I think you have the right idea. There is no such functionality available in the PGVectorStore class so you have to build it:

> subclassing the PGVectorStore+creating a custom retriever

I might start by making a copy of `vector_stores/postgres/base.py` rather than subclassing, because this will require modifying a bunch of things, e.g. the SQLalchemy data model. You'll need to create an index for the metadata fields you want to full-text search.

I would prefer to have a separate actual text column for each metadata field I wanted to search - which is more structure than the current approach, where all metadata lives in a JSON field (I believe this decision was driven by desire for LlamaIndex compatibility with multiple vector store backends).

Let me know what you come up with!

**Comment by coffepowered** [comment]
Thanks for your answer. I am actually wondering wether this is the correct approach (in principle).
In an ideal scenario, I'd like to offload this sort of thing to the vector db itself since the retrieval could get tricky quite quickly.


However, the combination of postgres extensions that would be ideal in this context (IMHO: pgvector+pg_search) is unavailable on the cloud vendor I am using due to licensing issues.

If I decide to do some tests, I'll share them here since you are also interested!
