### ISSUE TITLE
[Documentation]: PropertyGraph Missing image and bad link

### ISSUE THREAD

**Issue by nickknyc** [run-llama/llama_index#13869]
### Documentation Issue Description

Missing image here
https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_advanced/
![Screenshot 2024-05-31 130112](https://github.com/run-llama/llama_index/assets/1598572/05b7f0ed-4fe0-4f91-9142-f437b5acb8be)
Link takes you to 
https://docs.llamaindex.ai/en/stable/examples/module_guides/indexing/lpg_index_guide.md#construction
which looks like this
![image](https://github.com/run-llama/llama_index/assets/1598572/e44ecf48-46f0-44a3-8143-81d8a4802534)

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_advanced/

**Comment by logan-markewich** [comment]
Embedding images into notebooks, and then converting that to html, is always tricky. Not 100% I can fix the image thing (the [actual notebook is here](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/property_graph/property_graph_advanced.ipynb)), especially since this conversion is happening automatically with another library
