### ISSUE TITLE
[Question]:  Is it expected that `VectorStoreIndex.persist` and `load_index_from_storage` are not symmetric?

### ISSUE THREAD

**Issue by mpereira** [run-llama/llama_index#14028]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it expected that persisting (serializing) a `VectorStoreIndex` and then loading (deserializing) it is not symmetric?

In the code snippet below, `loaded_vector_store_index` is a `BaseIndex[Unknown]` while `vector_store_index` is a `VectorStoreIndex`. These classes have different behaviors.

For example, creating a query engine or retriever from each will have very different results. The ones coming from `VectorStoreIndex` having much better results.

```python
documents = [...]
nodes = markdown_parser.get_nodes_from_documents(documents)
vector_store_index = VectorStoreIndex(nodes=nodes)
vector_store_index.storage_context.persist(persist_dir="/tmp/vector_store_index")

embed_model = OpenAIEmbedding(api_key=os.environ["OPENAI_API_KEY"], model="text-embedding-3-small")
storage_context = StorageContext.from_defaults(persist_dir="/tmp/vector_store_index")
loaded_vector_store_index = load_index_from_storage(
    storage_context=storage_context,
    embed_model=embed_model,
)
```

I spent a lot of time today figuring this one out. I was seeing good results from the `vector_store_index` object in my ingester process, while my API process which was loading the result of ingestion into `loaded_vector_store_index` was showing really poor results.

To make it work, I'm manually creating a `VectorStoreIndex` from the `BaseIndex[Unknown]` in the API process:

```python3
nodes = loaded_vector_store_index.docstore.docs.values()
actual_loaded_vector_store_index = VectorStoreIndex(nodes=list(nodes))
```

Questions:
1. Is there a better way of doing this?
2. Am I missing something obvious?
3. Should `persist`/`load_index_from_storage` be symmetric?

**Comment by logan-markewich** [comment]
@mpereira The one thing I noticed, is that when creating the initial index, you do not set an embedding model, but then when loading it, you do. I suspect if you updated your code like this, it would be fine

```python
documents = [...]
nodes = markdown_parser.get_nodes_from_documents(documents)

# use the same embed model for both
embed_model =  OpenAIEmbedding(api_key=os.environ["OPENAI_API_KEY"], model="text-embedding-3-small")

vector_store_index = VectorStoreIndex(nodes=nodes, embed_model=embed_model)
vector_store_index.storage_context.persist(persist_dir="/tmp/vector_store_index")

storage_context = StorageContext.from_defaults(persist_dir="/tmp/vector_store_index")
loaded_vector_store_index = load_index_from_storage(
    storage_context=storage_context,
    embed_model=embed_model,
)
```

For a longer explanation on typing:
`load_index_from_storage` can return any index (a vector store index, property graph index, tree index, etc.) -- it works for all of them.

It knows what index to load because the index structure contains what type of index it is.

Because of how python typing works, `load_index_from_storage` has to have the return type of `BaseIndex` -- that's just how it is. And it is symmetrical, but you need to provide the proper embedding model that matches how the index was built.

**Comment by mpereira** [comment]
Hey @logan-markewich, thanks for the super quick reply.

I just tested it here. Your suggestion works. Thank you!

Feel free to close this.
