### ISSUE TITLE
[Question]: is there a way to return top k chunks in the order they appear in original document

### ISSUE THREAD

**Issue by vkaul11** [run-llama/llama_index#14212]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to use one document and get the positions of the indices in the document and arrange the top k to the llm in the order that they appear in the original document not by the similarity score. Is there a way to do so ? It would be really helpful for the llm.

**Comment by tonypeng1** [comment]
You can use the "start_char_idx" in a TextNode to arrange the retrieved nodes in the order they appear in the original document. A node that appears earlier in the document has a smaller value of "start_char_idx".

First, you define a llama index "Custom Node PostProcessor" class (the instruction can be found in this link. [https://docs.llamaindex.ai/en/stable/module_guides/querying/node_postprocessors/](url)) to sort the nodes according to the value of "start_char_idx". The code is as follows,
```
from llama_index.core import QueryBundle
from llama_index.core.postprocessor.types import BaseNodePostprocessor
from llama_index.core.schema import NodeWithScore

class SortNodePostprocessor(BaseNodePostprocessor):
    def _postprocess_nodes(
            self, 
            nodes: List[NodeWithScore], 
            query_bundle: Optional[QueryBundle]
            ) -> List[NodeWithScore]:
        
        # Custom post-processor: Order nodes based on the order they appear in a document (using "start_char_idx")

        # Create a new node dictionary
        _nodes_dic = [{"start_char_idx": node.node.start_char_idx, "node": node} for node in nodes]

        # Sort based on "start_char_idx"
        sorted_nodes_dic = sorted(_nodes_dic, key=lambda x: x["start_char_idx"])

        # Get the new nodes from the sorted node dic
        sorted_new_nodes = [node["node"] for node in sorted_nodes_dic]

        return sorted_new_nodes

```

Second, create a query engine with this new SortNodePostProcessor() as the "node_postprocessors". The code is as follows. (You can replace the fusion retriever below with another type of retriever.)
```
sort_engine = RetrieverQueryEngine.from_args(
    retriever=fusion_retriever, 
    node_postprocessors=[SortNodePostprocessor()],
    )
```
When this engine is used on a query, the original retrieved nodes will be sorted by the order they appear in the original document before being fed to the LLM.
```
sort_response = sort_engine.query(query_str)
```
You can check the newly ordered nodes by typing,
```
print(sort_response.get_formatted_sources(length=2000))
```

I found this custom node postprocessor helpful in improving the answer to the question "What are the things that happen in New York?" in the document "paul_graham_essay.pdf" (since the author was in New York in different years). I use this postprocessor to sort the 5 retrieved nodes by the fusion retriever (originally not ordered as they appear in the document), making the answer more reasonable in terms of the time sequence of the events that happen in New York.
