### ISSUE TITLE
[Bug]: Can not query top k similar documents from vector db

### ISSUE THREAD

**Issue by cuonglp1713** [run-llama/llama_index#14584]
### Bug Description

I have a vector db which stores my text, I want to create a search engine to input a text and get top k similar documents related to that input text. Here is my bug:
UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for  are not specified in config"},"time":0.000043331}'

### Version

0.10.52

### Steps to Reproduce

Here is my code:
```
vector_store = QdrantVectorStore(
    collection_name=QDRANT_COLLECTION,
    client=QdrantClient(url=QDRANT_URL)
)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_vector_store(
    vector_store=vector_store
)

query_engine = index.as_query_engine(
    similarity_top_k=5,
)

query_engine.query(question)
```

I don't follow those instruct like https://docs.llamaindex.ai/en/stable/module_guides/indexing/vector_store_index/ because I had store my data to vector db and now I want to use it to my search engine. All user guide use `index = VectorStoreIndex.from_documents(documents)` which requires data to create index and I don't prefer this

**Comment by logan-markewich** [comment]
Seems like an issue with either your qdrant version or your qdrant client version?

Do you have the full traceback?

**Comment by cuonglp1713** [comment]
@logan-markewich Im using qdrant-client version of 1.10.0. For qdrant I can't not check the image version now. But I don't think this causes by package version

**Comment by anoopshrma** [comment]
As @logan-markewich  mentioned, could you share the full traceback. That will help in debugging the issue.

**Comment by cuonglp1713** [comment]
I have found the bug. It's about getting wrong schema config for collection of vector db. I'm going to close issue now. Thank you for all of your support guys.

**Comment by cuonglp1713** [comment]
Helpful !

**Comment by vincentteyssier** [comment]
@logan-markewich 

I've reproduced it locally on latest qdrant and llamaindex version.

Here is the code and stack trace.
To be noted that this only happens if the data indexed in qdrant is hybrid (ie text-dense and text-sparse vectors)

HTTP Request: POST http://20.205.173.66:6333/collections/secfillings/points/search "HTTP/1.1 400 Bad Request"
Traceback (most recent call last):
  File "/home/baygon/qdranttest/main.py", line 61, in <module>
    retrieved_nodes = retriever.retrieve('annual revenues')
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py", line 245, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 103, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py", line 180, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/llama_index/vector_stores/qdrant/base.py", line 842, in query
    response = self._client.search(
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 387, in search
    return self._client.search(
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 563, in search
    search_result = self.http.points_api.search_points(
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 1820, in search_points
    return self._build_for_search_points(
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 852, in _build_for_search_points
    return self.api_client.request(
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 79, in request
    return self.send(request, type_)
  File "/home/baygon/qdranttest/venv/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 102, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for  are not specified in config"},"time":0.002823677}'


import logging
import sys
import os

import qdrant_client
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.core import StorageContext
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.embeddings.fastembed import FastEmbedEmbedding
from llama_index.core import Settings
from  llama_index.core.vector_stores import MetadataFilters, ExactMatchFilter
from llama_index.embeddings.huggingface import HuggingFaceEmbedding


# initialize embeddings and service context
Settings.embed_model = HuggingFaceEmbedding(model_name="WhereIsAI/UAE-Large-V1")

# init logging
logging.basicConfig(
    stream=sys.stdout, level=logging.INFO
)  # logging.DEBUG for more verbose output
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
_logger = logging.getLogger(__name__)

client = qdrant_client.QdrantClient(
    host="localhost",
    port=6333
)

print(client.info())

collection_name = "secfillings"
vector_store = QdrantVectorStore(client=client, collection_name=collection_name)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_vector_store(
    vector_store,
    storage_context=storage_context)


collections = client.get_collections()
_logger.debug(collections)

filters = MetadataFilters(filters=[
            ExactMatchFilter(
                key="ticker", 
                value='IVCA'
            )
        ])
retriever = index.as_retriever(similarity_top_k=5, filters=filters)
retrieved_nodes = retriever.retrieve('annual revenues')

**Comment by vincentteyssier** [comment]
Well, the solution was in my comment...
Since it is hybrid indexing, I should have passed enable_hybrid=True to the vector store

`vector_store = QdrantVectorStore(client=client, collection_name=collection_name, enable_hybrid=True,)`

This works fine.

If you have this issue and not using hybrid, then it is likely that you have named your vectors during indexing:

```
client.recreate_collection(
    collection_name="articles",
    vectors_config={
        "content": rest.VectorParams(
            distance=rest.Distance.COSINE,
            size=1536,
        ),
    },
)
```

In this example, my vectors are not using the default naming but instead use a key called "content"

I don't see any way to call a custom key in a qdrant retriever, but that would be the permanent fix.
As a workaround you can reindex your data not using any named key.

Here is the ticket on langchain that shows the issue:
https://github.com/langchain-ai/langchain/issues/2594
