### ISSUE TITLE
[Feature Request]: Upgrade Gemini LLM to be function calling for select Gemini LLMs

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_index#14993]
### Feature Description

According to Google, some of their Gemini models have function calling. In LlamaIndex this is set to False.

Gemini link: https://ai.google.dev/gemini-api/docs/function-calling
LlamaIndex code:
```
from llama_index.llms.gemini import Gemini

llm = Gemini(model = "models/gemini-1.5-pro-latest")
llm.metadata
```
This prints the cell:
```
LLMMetadata(context_window=2105344, num_output=8192, is_chat_model=True, is_function_calling_model=False, model_name='models/gemini-1.5-pro-latest', system_role=<MessageRole.SYSTEM: 'system'>)
```

### Reason

N/A

### Value of Feature

Gemini is currently free of charge (but rate limited) so having function calling would be a great help for quick prototyping.

**Comment by logan-markewich** [comment]
I welcome a contribution for this! I looked into it once and tbh found geminis api pretty confusing to implement the way that llama-index requires 

Vertexai in llama-indsx supports function calling though (so you can access gemini that way if you are using vertexai)

**Comment by ycd** [comment]
Gemini also has OpenAI compatibility for quite some time.

See: https://ai.google.dev/gemini-api/docs/openai

So we can use it like this:


```python
llm = OpenAI(
    model="models/gemini-2.0-flash",
    api_base="https://generativelanguage.googleapis.com/v1beta/openai/",
    api_key="GEMINI_API_KEY",
)

self.chat_engine = FunctionCallingAgent.from_tools(
    llm=llm,
    system_prompt=self.config.get_system_prompt(),
    tools=self.tools,
    verbose=True, 
)
```

However it simply does not works like this:

```python
Unknown model 'models/gemini-2.0-flash'. Please provide a valid OpenAI model name in: 
```

So I have to monkey-patch the codebase, which works just fine, for most cases. 

```python
import llama_index.llms.openai.utils as openai_utils


def get_context_size(model: str) -> int:
    gemini_models = {
        "models/gemini-2.0-flash": 10000000,
        "models/gemini-2.0-flash-exp": 10000000,
        "models/gemini-1.5-flash": 10000000,
        "models/gemini-1.5-flash-latest": 10000000,
    }
    return gemini_models[model]


openai_utils.CHAT_MODELS.update({"models/gemini-2.0-flash": 10000000})

import llama_index.llms.openai.base as openai_base

openai_base.openai_modelname_to_contextsize = get_context_size
```


The OpenAI's API compatibility has become a standard for many LLM provider(s), so I think it is quite limiting to have a model check, I know we can't have a generic solution because the `/v1/models` does not return enough thinks that LLamaIndex needs like checking the `context size`, `is_chat_model` etc, but it would be great to be able to disable those things on demand.

**Comment by SkeletonMask** [comment]
@ycd Thanks! This is worth a try

**Comment by aminebizid** [comment]
> FunctionCallingAgent

I tried this but I found that it didn't collect the tool calls from the gemini response :(
