### ISSUE TITLE
[Question]: how can i limit the VectorStoreIndex's from_documents resource usage?

### ISSUE THREAD

**Issue by atlas-comstock** [run-llama/llama_index#15018]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Question]: how can i limit the VectorStoreIndex's from_documents resource usage?

**Comment by logan-markewich** [comment]
Its hard to say without seeing your code

If you are using local embeddings, you'll want to set the batch size. For example
`HuggingFaceEmbedding(..., embed_batch_size=2)`

If you are indexing a lot data, you might want to use a dedicated vector store integration rather than using the default in-memory option
