### ISSUE TITLE
[Bug]: Workflow steps appear to be blocking?

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_index#15204]
### Bug Description

I might be wrong, but despite using proper async, workflow steps seems to be blocking execution.

### Version

llama-index-core==0.10.62

### Steps to Reproduce

```python
import asyncio
import time

from llama_index.core.workflow import (
    Context,
    Event,
    StartEvent,
    StopEvent,
    Workflow,
    step,
)


class MiddleEvent(Event):
    pass


class MiddleEvent2(Event):
    pass


class AsyncWorkflow(Workflow):
    @step(pass_context=True)
    async def start(self, ctx: Context, ev: StartEvent) -> MiddleEvent:
        for i in range(9):
            self.send_event(message=MiddleEvent())
        return MiddleEvent()

    @step(pass_context=True)
    async def middle(self, ctx: Context, ev: MiddleEvent) -> MiddleEvent2:
        await asyncio.sleep(0.5)
        return MiddleEvent2()

    @step(pass_context=True)
    async def end(self, ctx: Context, ev: MiddleEvent2) -> StopEvent:
        result = ctx.collect_events(ev, [MiddleEvent2] * 10)
        if result is None:
            return None
        return StopEvent()


async def main():
    w = AsyncWorkflow(verbose=True)
    start = time.time()

    await w.run()
    end = time.time()
    print(f"Time taken: {end - start}")


if __name__ == "__main__":
    asyncio.run(main())
```

### Relevant Logs/Tracbacks

```shell
It takes ~5s to run, when in reality I would expect ~0.5s
```

**Comment by logan-markewich** [comment]
The issue here is, we only have one instance of a step, which essentially means a single worker per step.

We can increase concurrency for example, if we spawn more than one worker/task for each step
For example, adding this to the source code, it takes 0.5s as expected:
```
for _ in range(10):
    self._tasks.add(
        asyncio.create_task(
            _task(name, self._queues[name], step_func, step_config), name=name
        )
    )
```

Perhaps we need a `num_workers` param in the step decorator
```
@step(..., num_workers=4)
```

**Comment by Tonyrj3268** [comment]
I am bringing this up on Discord because I need the LLM to break down my main question into n sub-questions, so dynamic consumers are what I need.

Of course, I believe that pre-defining the number of potential consumers may be sufficient for most scenarios, but dynamic addition might be better?

Perhaps modifications to send_event could be a solution, as this is currently the only reason for generating a large number of producers simultaneously, or maybe adding a monitoring role could help as well.

I am looking forward to the continued improvement of the workflow and hope to contribute to it.
