### ISSUE TITLE
[Question]: How to handle complex PDFs

### ISSUE THREAD

**Issue by cxycxm** [run-llama/llama_index#15243]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to handle complex PDFs，such as PDFs with images, tables, etc.

**Comment by cxycxm** [comment]
https://readers.llmsherpa.com/api/document/developer/parseDocument?renderFormat=all

**Comment by kotechile** [comment]
Can I use smartPDFLoader without calling llmsherpa_api_url = "https://readers.llmsherpa.com/api/document/developer/parseDocument?renderFormat=all" ?  Is it possible to use it directly integrated with LlamaIndex/ LLama Parse?

**Comment by filmo** [comment]
It seems like llmsherpa.com URL is dead. As such using the solution above is no longer valid as near as I can tell or at the very least requires a rework.

It seems like llmsherpa now needs to connect to a local api. See: https://github.com/nlmatics/nlm-ingestor

Adding this note because the RunLLM support chatbox is directing inquries about ingesting PDFs with structure to this GitHub issue.
