### ISSUE TITLE
[Question]: Ingestion Pipelines and Workflows?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#15401]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is the `IngestionPipeline` impacted by workflows at all or is it strictly `QueryPipeline`?

**Comment by logan-markewich** [comment]
@brycecf actually, despite the name, the ingestion pipeline is neither a query pipeline or a workflow.

Probably at some point, we could consider making it a workflow so that it's more dynamic, but a little unsure what that will look like just yet. Maybe just something like `IngestionPipeline(workflow=workflow, ...)` rather than specifying transformations?
