### ISSUE TITLE
[Question]: LlamaIndex with OpenSearch: MetadataFilters not working as expected

### ISSUE THREAD

**Issue by Blandrust** [run-llama/llama_index#15433]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using LlamaIndex as a knowledge base with OpenSearch as the vector store. Everything works fine until I try to add MetadataFilters to my query. Here's my current query function:

```python
def query_index(query: str, indexName: str):
    index = vectorstore_cache.load_index(indexName)
    category = select_category(query, indexName)
    
    filters = MetadataFilters(filters=[
        MetadataFilter(
            key="category", 
            value=category.name
        ),
    ])
    retriever = index.as_retriever(
        choice_batch_size=5,
        filters=filters,
        vector_store_query_mode=VectorStoreQueryMode.HYBRID,
    )
    result = retriever.retrieve(query)
    return result
```
Without filters, the function retrieves documents as expected. However, when I add the filters, I get this error:

`RequestError: RequestError(400, 'x_content_parse_exception', '[category] query malformed, no start_object after query name')`

I logged the query sent to OpenSearch, and it looks something like this:

```python
{
    'size': 2, 
    'query': {
        'hybrid': {
            'queries': [
                {
                    'bool': {
                        'must': {'match': {'content': {'query': 'x?'}}},
                        'filter': [{'category': 'y'}]
                    }
                },
                {
                    'script_score': {
                        'query': {'bool': {'filter': [{'category': 'y'}]}},
                        'script': {
                            'source': "1/(1.0 + l2Squared(params.query_value, doc['embedding']))",
                            'params': {'field': 'embedding', 'query_value': [-0.026000717654824257, ...]}
                        }
                    }
                }
            ]
        }
    }
}
```
I believe the filter should look more like this:

```json
"term": {
    "category": "y"
}
```
Is there a way to modify how LlamaIndex constructs the filter query for OpenSearch? Or am I misunderstanding how to use MetadataFilters with OpenSearch?
Any help or guidance would be greatly appreciated. I'm not sure if this is a LlamaIndex issue or if I'm missing something in my OpenSearch configuration. Thank you in advance for your assistance!

**Comment by sad-mathematician** [comment]
@Blandrust There was a bug in how llama_index handled metadata filtering with opensearch. I believe it has been fixed last week. So your problem should be solved if you simply upgrade to the latest llama_index version.
If you don't want to upgrade right now, you will need to update the _parse_filters method of the OpensearchVectorClient class where the problem is. 
The filter should look like:
```
'filter': [{'term': {'metadata.category': 'y'}}]
```
It needs the `term` key around the metadata with `metadata.` added as a prefix to the filter key.

```
from llama_index.vector_stores.opensearch import OpensearchVectorStore, OpensearchVectorClient

# Creating a new _parse_filters method to fix the default methods
def new_parse_filters(self, filters: Optional[MetadataFilters]) -> Any:
        pre_filter = []
        # print(filters)
        if filters is not None:
            for f in filters.legacy_filters():
                if isinstance(f.value, list):
                    pre_filter.append({"terms": {f.key: f.value}})
                elif isinstance(f.value, str):
                    pre_filter.append({"term": {f.key: f.value}})
                else:
                    pre_filter.append({f.key: json.loads(str(f.value))})

        return pre_filter

OpensearchVectorClient._parse_filters = new_parse_filters
```

This should format the filters properly for now. Remember, before the recent fix, in MetadataFilter, the key had to be `metadata.` followed by the name. So `metadata.category` in your case. Though you don't have to do this if you just upgrade the llama_index version.

note: the answer given by dosu bot is based on this latest version where the metadata filtering has been fixed and might not be relevant to your question about a previous version. Upgrading would be the best way to solve your problem.

**Comment by logan-markewich** [comment]
This is solved if you update: `pip install -U llama-index-vector-stores-opensearch`
