### ISSUE TITLE
[Question]: Is there a reason why the OpensearchVectorClient runs exclusively using async code?

### ISSUE THREAD

**Issue by kobiche** [run-llama/llama_index#15922]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Like others (see #10719) I had some issues running my code using the OS-VectorClient as database. I have seen in the code this only runs using async code. Why? 
If I check the code in [LangChain](https://github.com/langchain-ai/langchain/blob/c03fd93fc1fe29bc4991c54f3d2159c5eb9a9d9b/libs/community/langchain_community/vectorstores/opensearch_vector_search.py), they give sync and async possibilities. Can we adjust the code in LlamaIndex to offer both possibilities?

**Comment by logan-markewich** [comment]
I don't have access to opensearch to make the changes or test, but I welcome a PR

**Comment by GeorgeDittmar** [comment]
I'm tempted to put in a PR to handle this. I had to rewrite the OpensearchClient and Vectorstore classes myself to remove the async calls cause they were failing under fastapi due to nested event loops. I can try to start this sometime this week and maybe just set a flag to make sure we use the sync or async opensearch-py libs.

**Comment by kobiche** [comment]
I have most of changes ready. I'll try post a PR tomorrow

**Comment by logan-markewich** [comment]
fyi you are going to want async for any production-ready server 😅 

Nested async can be solved by either not using async entry points, or using `nest_asyncio.apply()` and `uvicorn.run(..., loop="asyncio")` 

Caveat here is that only the ingestion pipeline and and vector store object directly use `vector_store.async_add()` when indexing data 😅

**Comment by GeorgeDittmar** [comment]
does hat uvicon loop argument work for command line call to uvicorn or just api call?

**Comment by GeorgeDittmar** [comment]
So setting the event loop flag in uvicorn still throws errors under fastapi and same with nest_asyncio.apply().

**Comment by kobiche** [comment]
> fyi you are going to want async for any production-ready server 😅

However, I don't see the advantage of using the async code here, since each function has its own `event_loop.run_until_complete(...)`. I thought the only way to really take advantage of async is to make the whole program async.

**Comment by GeorgeDittmar** [comment]
for my 2 cents, while i agree things like async threading is needed for high throughput production systems, doesnt really mean we shouldnt also support sync use cases. like I stated above the current opensearch support fails under FastApi due to nested async calls and trying the suggestions above do not seem to resolve it so only other option I have available at this moment is sync with threading.

**Comment by kobiche** [comment]
Since my PR was merged (thanks @logan-markewich!), I will close my question.
