### ISSUE TITLE
[Question]: Calculated available context size -N was not non-negative

### ISSUE THREAD

**Issue by nbahar-intel** [run-llama/llama_index#16235]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,
I'm having this issue whenever I reach to the point that my chat exceeds X amount of tokens.

I was assuming `as_chat_engine()` set up with `max_prompt` which preserves chat history, would automatically handle this situation.

What am I missing ?

**Comment by nbahar-intel** [comment]
@dosu I was assuming it would truncate automatically, is that not the case? If not, how can I truncate it? Do I need to define a custom PromptHelper?

**Comment by nbahar-intel** [comment]
@dosu How do I make sure it automatically truncates, obviously in my case it doesn't?
Here is an example of my current flow:
```python
        llm = MyLlamaCustomIndex(...) 
        Settings.llm = llm  # Set the llm.
        index = VectorStoreIndex.from_documents(documents, show_progress=True, insert_batch_size=50, chunk_size_limit=256)
        prefix_messages = [ChatMessage(content=msg.content, role=msg.role) for msg in chat.messages]
        index.QE().as_chat_engine(chat_history=prefix_messages, verbose=False, streaming=True, chat_mode=ChatMode.CONDENSE_PLUS_CONTEXT, chunk_size_limit=256, similarity_top_k=2)
        stream_response = index.stream_chat(prompt)
```

**Comment by logan-markewich** [comment]
@nbahar-intel what LLM are you using? What is `MyLlamaCustomIndex` ? There's probably some setup here that we can fix or improve

It should be handled automatically, but depending on the LLM you are using, you can get into situations where there is no way to handle the input. There's no way to force truncation because what do you truncate? The prompt template? The context? The query? 

Seems like to me you might need to setup your memory to have a lower token limit for chat-history, or perhaps your custom LLM is not defining its context window properly

**Comment by nbahar-intel** [comment]
> @nbahar-intel what LLM are you using? What is `MyLlamaCustomIndex` ? There's probably some setup here that we can fix or improve
> 
> It should be handled automatically, but depending on the LLM you are using, you can get into situations where there is no way to handle the input. There's no way to force truncation because what do you truncate? The prompt template? The context? The query?
> 
> Seems like to me you might need to setup your memory to have a lower token limit for chat-history, or perhaps your custom LLM is not defining its context window properly
Unfortunately I can't publicly share any related code to it, but I can say it inherits from CustomLLM and defines the common methods to stream, stream_complete, client, API requests etc..
Would love for your input on how to set it up properly though

**Comment by nbahar-intel** [comment]
As far as I could notice tho, it doesn't define `context_window` in the `metadata` it overrides, hence it uses the default `3900` by `DEFAULT_CONTEXT_WINDOW` (`llama_index\core\base\llms\types.py`)

**Comment by logan-markewich** [comment]
Are you able to share how you setup the `metadata` property?

```
@property
def metadata(self) -> LLMMetadata:
    """Get LLM metadata."""
    return LLMMetadata(
        context_window=self.context_window,
        num_output=self.num_output,
        model_name=self.model_name,
    )
```

The context window and num_outputs are very important -- the context window should accurately reflect the context window of the LLM. And if its low, thats ok, but that means you should be likely control the size of the memory buffer a bit more for that chat history

**Comment by logan-markewich** [comment]
(If you can at least share the LLM you are using, llama3.1, etc. I can help point towards the correct context window size)

**Comment by nbahar-intel** [comment]
LLM used is GPT-4o under the hood
Currently ->
```python
    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        print("Tried to access metadata")
        return LLMMetadata(
            model_name=self.model
        )
```

**Comment by logan-markewich** [comment]
can you set the context window to the actual gpt-4o size then?

Something like

```
   @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        print("Tried to access metadata")
        return LLMMetadata(
            context_window=128000,
            model_name=self.model
        )
```

**Comment by nbahar-intel** [comment]
That solved the issue. Thank you!
Just general question before I close this issue, what happens when conversation would hit that limit as-well?

**Comment by logan-markewich** [comment]
It shouldn't hit that limit 😅 I don't force this issue coming back, but if it does, you probably want to lower the `token_limit` on the `ChatMemoryBuffer` for the chat engine -- `as_chat_engine(..., memory=ChatMemoryBuffer.from_defaults(token_limit=50000)` maybe


Longer explanation below:

The issue you were seeing before stems from a lot of things, let me explain


- by default, every chat engine uses a `ChatMemoryBuffer` to store a buffer of the previous conversation. There is a token limit, which is by default, 75% of the LLM context window
- on every `.chat()` call, it gets the memory buffer, and uses it to dynamically make a prompt template for a response synthesizer -- the template includes the chat history, and template variables for the retrieved context and latest user message
- by default, its using the `Compact` response synthesizer -- what this does is takes the prompt templates + retrieved context, and "compacts" it into as few LLM calls as possible. Obviously as your chat history grows, so will the size of the template, and it this repacking process may require more than one chunk
- the error here was happening because the prompt template with chat history was already bigger than the context window of the llm (or, the default context window that you left)

So, 75% of 3900 is pretty small, and doesn't leave a lot of room for retrieved context

75% of 1280000 is pretty big, and leaves lots of room for retrieved context, which is why its less of a problem

**Comment by nbahar-intel** [comment]
You've been a great help over the last couple of days. Thank you!

**Comment by LydiaLiu0001** [comment]
@dosu,there is no chatmessage and chatmode modules exist in llama_index.core
