### ISSUE TITLE
[Feature Request]: Why can FunctionCallingProgram only pass in one tool?

### ISSUE THREAD

**Issue by dcdmm** [run-llama/llama_index#16287]
### Feature Description

tool = _get_function_tool(self._output_cls)

messages = self._prompt.format_messages(llm=self._llm, **kwargs)
messages = self._llm._extend_messages(messages)

agent_response = self._llm.predict_and_call(
    [tool],
    chat_history=messages,
    verbose=self._verbose,
    allow_parallel_tool_calls=self._allow_parallel_tool_calls,
    **llm_kwargs,
)

predict_and_call can accept multiple tools, why can only one tool be passed in here?The tool call in langchain can pass in multiple pydantic objects

**Comment by dcdmm** [comment]
??

**Comment by logan-markewich** [comment]
@dcdmm because that's for the programs work

Use llm.chat_with_tools or llm.predict_and_call if you want to call more than one 


Predict and call
https://docs.llamaindex.ai/en/stable/examples/llm/openai/#function-calling

Example of a full function calling agent, that uses chat_with_tools, parses out the tool calls, and calls them
https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/
