### ISSUE TITLE
[Question]: Any Benefit to Exposing a Workflow as a QueryEngine?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#16854]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

@logan-markewich had mentioned awhile ago that the original plan for the Query Engines going forward was to reimplement them using Workflows.  That was later dropped as being unnecessary.

With that being said, is there a particular benefit to exposing a Workflow as a `BaseQueryEngine` (beyond when a `BaseQueryEngine` type may be expected by some class/function?

There is a definite downside in that it is rather tricky for a QueryEngine to support multi-inputs, which can be done with both `QueryPipeline` and `Workflow`, so it can limit that when exposed as a QueryEngine.  Consequently, I'm trying to understand if anything would offset that sacrifice.

**Comment by logan-markewich** [comment]
I think the only downside is the types as you mentioned. Having an expected interface is nice so that the workflow plays nice with things that expect a query engine

That being said, there's nothing stopping you from using CustomQueryEngine and wrapping a workflow into it if you need the query engine type
