### ISSUE TITLE
[Question]: Alternative Methods for Report Generation Using LLMs Without LlamaParse or LlamaCloud?

### ISSUE THREAD

**Issue by LikhithRishi** [run-llama/llama_index#16922]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I’m currently working on generating reports using large language models (LLMs) and would like to explore alternatives that don’t rely on LlamaParse or LlamaCloud. Are there any other recommended libraries, tools, or techniques that are open-source or free to use for effective report generation using LLMs?

**Comment by logan-markewich** [comment]
@LikhithRishi You can replace the components in any report-gen tutorial with local equivalents (unstructured, docling, or marker for parsing, literally any vector db for retrieval). It will probably work a little less better though, since llama-cloud/llama-parse are heavily optimized for their specific use cases
