### ISSUE TITLE
[Question]: How to avoid loading my model everytime?

### ISSUE THREAD

**Issue by HairlessVillager** [run-llama/llama_index#17142]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello everyone,

I apologize if my question seems simple or naive. 😅

I'm currently developing a script that loads models (downloaded from HuggingFace) each time it runs. However, loading the necessary models takes approximately 30 seconds, which is unacceptable for my rapid development process.

I've tried using Ollama, which allows models to reside in GPU memory. Unfortunately, Ollama doesn't support the models I'm using.

A potential solution I'm considering is starting another process that holds the model in GPU memory and performs inference. My script could then communicate with this process via HTTP APIs. However, I'm new to LlamaIndex and could use some help. Can anyone give me some advice?

Thank you!🥰

**Comment by hristogg** [comment]
I am not sure I fully understand the details, however I will try to give an idea anyway hope it's not completely far off :)

One approach would be as you have mentioned to have a running service (e.g. Flask) on same machine/different machine which is always live and you can do an HTTP request to that service so that you do not deal with this inside your llamaindex pipeline.

I am guessing you could also look at workflow deployment through llama-deploy, I guess if you make your code into a workflow it will be loaded once and you can run the workflow through an HTTP call as well, doing whatever you are doing.

**Comment by HairlessVillager** [comment]
@hristogg Thanks!🥰I'll take a look

**Comment by logan-markewich** [comment]
@HairlessVillager another option is an optimized server dedicated for models, like TGI and TEI from huggingface, or vllm. I think this is a fairly common practice
