### ISSUE TITLE
[Feature Request]: Create Elasticsearch VectorStore

### ISSUE THREAD

**Issue by jeffvestal** [run-llama/llama_index#6441]
### Feature Description

Create Elasticsearch Vector store
- Create index to store vectors with correct mapping
-- option for exact match and knn dense_vector settings
- delete index
- perform exact match (script score) vector search
- perform approximate kNN vector search
- Generate embeddings from Elasticsearch hosted embedding model

### Reason

Elasticsearch supports vector search (exact and kNN) and can be used as a vector database

**Comment by jon-chuang** [comment]
Can the same underlying data be indexed with both vector embeddings and traditional inverted index search like BM25? Do you end up paying the same cost as though you were indexing two separate datasets?

**Comment by jon-chuang** [comment]
Hello @jeffvestal , any progress on this?

We are quite interested in Elastic's Learned Sparse Encoder: https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-elser.html

**Comment by mgaruccio** [comment]
Just came across this issue while looking to see if a few features are planned to be supported in llama-index for elasticsearch.  The main feature of interest for me and my team is elastic's hosted embedding models, which allow for doc ingestion without having to generate the embeddings locally or via an additional API (and will eventually allow for things like generating new embeddings from existing data.

I can also answer some of @jon-chuang's questions around elastic's vector implementation in case they haven't been already.  The data is stored alongside the normal document so the only additional storage consumed is the storage in-use by the vector field, and you are able to perform both a knn and bm25 search at the same time, with elastic using rrf to combine the results.

I'm working on making some adjustments to the elastic implementation to support hosted embedding models (which should also enable elser) and hope to have  PR in a day or so.

**Comment by mgaruccio** [comment]
Actually I just realized that the embedding support exists, it just needs to be used in a somewhat non-intuitive way if you're coming form the langchain implementation.  For anyone else who stumbles on this looking for information using the hosted models for generating embeddings those exist here - https://docs.llamaindex.ai/en/stable/examples/embeddings/elasticsearch.html

That would also allow elser to be used since it is just treated like any other model.

Apologies for bumping this for something that was already implemented.
