### ISSUE TITLE
SubQuestionQueryEngine: Equivalent of RetrievalQAWithSourcesChain and printing intermediate results in streamlit

### ISSUE THREAD

**Issue by hsmsci** [run-llama/llama_index#7978]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using SubQuestionQueryEngine for chat with pdf functionality. I need help with a couple of things:
1) Is there an equivalent of RetrievalQAWithSourcesChain from Langchain in Llamaindex? What I want is that the response should also return sources that were used to draft the response with specific page number, so that users can scroll to that part and get additional info as needed. Something similar to what they have implemeneted here: https://chat.langchain.com/

2) When I run the subquestion query, it does show me the intermediate results in python notebook. But when I try the same code in a streamlit app, the intermediate steps don't appear. Is there a way to stream the intermediate steps in realtime and output it on streamlit ?

**Comment by logan-markewich** [comment]
You need to use a callback to achieve both of these. We did the same in our SEC-Insights demo app

https://github.com/run-llama/sec-insights/blob/e7f20213c60984dec2d25106ae4c3501e19c88c0/backend/app/chat/messaging.py#L33

I can make a PR to add the source nodes to the response object though. But the callback will give you the most direct results.

The sub-steps are only printed to console, which is why you don't see it in your streamlit app.

**Comment by hsmsci** [comment]
Thank you @logan-markewich , this is helpful
