### ISSUE TITLE
[Bug]: Arize Phoenix non-default port only works when set through the environment PHOENIX_PORT

### ISSUE THREAD

**Issue by aerickson-clt** [run-llama/llama_index#7985]
### Bug Description

You can set the Phoenix port in code or in the environment, and that will launch the Phoenix app to that port.  However, Llama Index will only use the default port 6060 unless the Phoenix port is set in the environment.  If you set the Phoenix port in code only, Llama Index's callback won't communicate with Phoenix.

```
if os.getenv("PHOENIX_IS_ON") == "TRUE":
    import phoenix as px
    from llama_index import set_global_handler
    session = px.launch_app(port=6081) # <--- this alone doesn't help
    set_global_handler("arize_phoenix")
```

You need this:
Environment
```
PHOENIX_PORT=6081
```

### Version

839.post1

### Steps to Reproduce

You can probably reproduce with the phoenix tutorial

https://docs.llamaindex.ai/en/stable/end_to_end_tutorials/one_click_observability.html
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb

I am using an Azure OpenAI gpt 3.5 turbo, but I doubt this would change anything...

**Comment by mikeldking** [comment]
hi @aerickson-clt one of the maintainers of phoenix (https://github.com/Arize-ai/phoenix). Glad you tried it out!

We have the port documented but agree it's kinda confusing that you would have to use the environment variable instead of the parameter in the case of traces. In the cases the tracer's exporter and the phoenix app need to talk on the same port so this is why it fails.

https://docs.arize.com/phoenix/api/session#environment-variables

Hope that helps and let me know if anything else needs clarifying.
