### ISSUE TITLE
[Question]: Llama_index fails to recognize number of pages in a pdf

### ISSUE THREAD

**Issue by tytung2020** [run-llama/llama_index#8081]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

as seen in this screenshot, there are 21 pages, but when asked via Davinci, it says only 3 pages:

![Screenshot (588)](https://github.com/run-llama/llama_index/assets/37324680/bdcaee9a-f91f-43df-9ae2-b37f34b64cc7)

**Comment by logan-markewich** [comment]
A vector index inherently cannot answer this question.

A vector index retirves the top k (default 2) most relevant text chunks compared to your query, and sends the text + query to the LLM.

Following this, it's impossible to answer a question like that with a vector index.

You could add the total pages (and other document info) as metadata to the input document objects, so that the retrieved text chunks also have this information

Or if you were creating an agent, you could have a custom tool for getting document info like this

**Comment by logan-markewich** [comment]
More details on metadata https://gpt-index.readthedocs.io/en/stable/core_modules/data_modules/documents_and_nodes/usage_documents.html#customizing-documents

**Comment by tytung2020** [comment]
Thanks, so any vector database + embedding approach by itself could not answer metadata queries like this?

**Comment by logan-markewich** [comment]
Correct, not unless you attach metadata to the nodes
