### ISSUE TITLE
[Documentation]: test dependencies for developers

### ISSUE THREAD

**Issue by david20571015** [run-llama/llama_index#8508]
### Documentation Issue Description

`data_requirements.txt` was removed in #8501, but the instructions in the CONTRIBUTING.md#testing still have developers to install it.

### Documentation Link

https://github.com/run-llama/llama_index/blob/main/CONTRIBUTING.md#testing

**Comment by jamesbraza** [comment]
@david20571015 nice catch, looks like I missed that. The correct instructions are now:
- Here https://github.com/run-llama/llama_index/pull/8501/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R136-R139
- Or here: https://github.com/run-llama/llama_index/blob/main/CONTRIBUTING.md#environment-setup

Any chance you'd be willing to open a PR to fix `CONTRIBUTING.md` to:

```bash
pip install poetry
poetry install --with dev
make test
```

**Comment by jamesbraza** [comment]
Oh yeah

**Comment by jamesbraza** [comment]
Thanks for that PR! 👍 

The issue you are actually hitting is quite similar to https://github.com/run-llama/llama_index/issues/8242, where:

- Incomplete dependencies lead to CI skipping tests
    - The skipped test would've failed in CI, but because they were skipped it doesn't show up
- During local development with dependencies installed, the tests are run and do fail

To address #8242, I made https://github.com/run-llama/llama_index/pull/8263 earlier this week actually.

I agree with you that the current asymmetry between CI and local dev will repeatedly lead to issues. I brought this up in https://github.com/run-llama/llama_index/issues/8264, if you're curious.

---

As far as that `if "CI" in os.environ:` in `test_code_splitter`, looking at the `git blame` it's been there since its addition in https://github.com/run-llama/llama_index/pull/7223.  I don't know why the original devs chose to skip these tests in CI.

---

To handle the exact issues you're facing in `test_code_splitter`/`test_bedrock`, for now we fix them on a case-by-case basis.

For `test_code_splitter`, there's a few possible routes:

- Option 1: add the missing dependencies to the poetry `dev` group in `pyproject.toml`
- Option 2: actually fix the tests to not require the dependencies, so they get run in CI
    - My suggested technique here is to use `unittest.mock.patch`: https://github.com/run-llama/llama_index/blob/v0.8.53.post3/tests/llms/test_huggingface.py#L12-L13

For `test_bedrock`, without reading further, you'll need to figure out how to add a stub region within testing.  See https://github.com/run-llama/llama_index/pull/8263 for how I solved a similar issue earlier this week.

**Comment by david20571015** [comment]
Thank you for your detailed response. Is the task of fixing `test_code_splitter`/`test_bedrock` currently in progress, or should I open a pull request to fix it?

**Comment by jamesbraza** [comment]
Feel free to open a PR! 💪
