### ISSUE TITLE
[Question]: llm and embed_model in service_context for index

### ISSUE THREAD

**Issue by Phil-U-U** [run-llama/llama_index#8658]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When the index is configured by service_context which specifies both llm and embed_model:

0. Do we need both llm and embed_model for indexing?
1. Is embed_model necessary for indexing?
2. If No. 1 is true, how does embed_model work together with llm?

Feel free to comment with the relevant code. 

Thank you in advance!

**Comment by logan-markewich** [comment]
@Phil-U-U it really depends on the index. 

The vector index really only needs the embed model for indexing.

The tree index needs the LLM

A knowledge graph index can use both (uses the LLM to generate triplets and then embeds them with the embed_model)

Due to how the service context is setup currently, both are always initialized regardless of if they are used. You can explicitly disable them by setting them to `None` though: `ServiceContext.from_defaults(llm=None)`
