### ISSUE TITLE
[Question]: Make agents faster on processing query engine replies

### ISSUE THREAD

**Issue by ElioErrico** [run-llama/llama_index#8680]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello everybody, do you have strategies to have the agents to process more quickly answers when context is coming from query engines?  The  answer of a query engine in my case can take also 25 seconds, I wonder if is like this for everybody, here a simple code example: 

```
query_engine_tool =QueryEngineTool(
        query_engine=vector_query_engine,
        metadata=ToolMetadata(
            name=f"{documento}_vector_tool",
            description=f"use this tool when ... bla bla bla'",
            ))
    
llm = OpenAI(model="gpt-3.5-turbo-0613",temperature=0)

agent = OpenAIAgent.from_tools(
    [query_engine_tool], llm=llm, verbose=True,
    system_prompt=custom_system_prompt
)
```

**Comment by gich2009** [comment]
Test conditions:
1. GPT 3.5 turbo
2. Chat engine in context mode.

Issue: 
>=v0.8.57 responses are very verbose therefore:
1. The speed is reduced
2. The context keeping is degraded.


Test cases:
            [
              {"prompt": "Who is ACMI?"},
              {"prompt": "What do they do?"},
              {"prompt": "Cool, why is it important?"},
            ]

Response for v0.8.56:
###Response 1
ACMI refers to the Africa Carbon Markets Initiative. It is a coalition of organizations focused on climate impact, clean energy, and sustainable development. The initiative was launched by the Global Energy Alliance for People and Planet (GEAPP), Sustainable Energy for All (SEforALL), and the United Nations Economic Commission for Africa (UNECA), with support from the UN Climate Change High-Level Champions. ACMI aims to accelerate the growth of Africa's voluntary carbon markets and is led by a 13-person steering committee of influential African leaders and carbon market experts.


###Response 2
The Africa Carbon Markets Initiative (ACMI) works towards accelerating the growth of voluntary carbon markets in Africa. Their main objectives include:

1. Promoting sustainable development: ACMI aims to support projects and initiatives that contribute to sustainable development in Africa, such as renewable energy projects, energy efficiency measures, and sustainable agriculture practices.

4. Facilitating access to carbon finance: ACMI seeks to enhance access to carbon finance for African businesses and organizations by providing guidance, capacity building, and technical assistance. They aim to help African entities navigate the complexities of carbon markets and develop projects that generate carbon credits.

5. Building capacity and knowledge: ACMI focuses on building the capacity of African stakeholders, including governments, businesses, and civil society organizations, to participate effectively in carbon markets. They provide training, workshops, and knowledge-sharing platforms to enhance understanding and expertise in carbon finance and project development.

6. Advocacy and policy support: ACMI advocates for supportive policies and regulations that enable the growth of carbon markets in Africa. They engage with policymakers, governments, and international organizations to promote favorable conditions for carbon market development and implementation.

Overall, ACMI plays a crucial role in promoting sustainable development, facilitating access to carbon finance, building capacity, and advocating for supportive policies to drive the growth of voluntary carbon markets in Africa.


###Response 3
The Africa Carbon Markets Initiative (ACMI) is important for several reasons:

1. Climate change mitigation: ACMI focuses on promoting projects and initiatives that reduce greenhouse gas emissions. By facilitating access to carbon finance and supporting the development of sustainable projects, ACMI contributes to mitigating climate change and reducing the carbon footprint of African countries.

2. Sustainable development: ACMI's efforts align with the United Nations Sustainable Development Goals (SDGs). By promoting sustainable practices in sectors such as renewable energy, energy efficiency, and agriculture, ACMI helps African countries achieve sustainable development objectives, including poverty alleviation, access to clean energy, and environmental conservation.

4. Economic opportunities: Voluntary carbon markets provide economic opportunities for African businesses and organizations. By participating in carbon markets, African entities can generate revenue through the sale of carbon credits, which can be reinvested in sustainable projects and contribute to local economic growth.

5. Capacity building and knowledge transfer: ACMI's focus on building capacity and knowledge in carbon finance and project development helps African stakeholders gain expertise in these areas. This empowers them to effectively participate in carbon markets, attract investment, and implement sustainable projects, leading to long-term economic and environmental benefits.

7. International cooperation and collaboration: ACMI's work involves collaboration with international organizations, governments, and stakeholders. This fosters partnerships and knowledge exchange, enabling African countries to benefit from global best practices, technologies, and funding opportunities in the field of climate change mitigation and sustainable development.

Overall, ACMI's activities are important for addressing climate change, promoting sustainable development, creating economic opportunities, building capacity, and fostering international cooperation in Africa's transition to a low-carbon and sustainable future.

Time taken: 75.96979494199331 seconds



Response for v0.8.61(or any >=v0.8.57):
###Response 1:
The Africa Carbon Markets Initiative (ACMI) is a coalition of organizations focused on climate impact, clean energy, and sustainable development. It aims to accelerate the growth of Africa's voluntary carbon markets. ACMI is led by a 13-person steering committee of influential African leaders and carbon market experts. The initiative aims to support the scaling of high integrity African carbon credits, create jobs, and support energy access, biodiversity, and livelihoods. ACMI is developing a roadmap of action programs to be implemented in the coming years, covering all aspects of the voluntary carbon market ecosystem. Integrity is a central focus for ACMI, and it will work with leading bodies to establish transparency and benefits-sharing standards. ACMI is not meant to compete with existing initiatives but rather to build on and reinforce ongoing efforts to scale voluntary carbon markets in Africa. The initiative intends to represent the broader voluntary carbon markets ecosystem and not individual organizations. ACMI's sponsors, partners, and steering committee members agree to disclose any potential direct benefits and recuse themselves from any efforts that could directly benefit themselves or their organizations. ACMI proposes action programs to scale project developers, develop national enabling ecosystems, build validation and verification capacity, create a more integrated African carbon market, reduce costs, leverage advanced market commitments, carbon neutral commodities, and advocacy to fuel demand for African credits. Cross-cutting action programs will pilot new project types and methodologies and explore diversified financing models for nature assets. Carbon credit integrity is a critical area of focus for ACMI, and it will work with leading bodies to establish transparency and benefits-sharing standards.


###Response 2:
The role of carbon credits is to help reduce greenhouse gas emissions and combat climate change. Carbon credits are a form of tradeable permits that represent the right to emit one tonne of carbon dioxide or an equivalent greenhouse gas. They are used as a way to incentivize and finance projects that reduce emissions, such as renewable energy projects or energy efficiency initiatives.

Carbon credits are generated through offset projects, which are projects that reduce or remove greenhouse gas emissions. These projects are approved and certified by regulatory bodies or non-governmental organizations. The offset projects follow specific frameworks and protocols to ensure that they meet environmental standards and requirements.

Once an offset project is approved and certified, it can generate carbon credits. These credits can then be bought and sold on the carbon market. Companies or individuals that need to offset their own emissions can purchase these credits to compensate for their carbon footprint.

The carbon credit market is divided into compliance markets and voluntary markets. Compliance markets are regulated by international or governmental bodies and are used to meet mandatory emission reduction targets. Voluntary markets, on the other hand, are not regulated and are used by companies or individuals who want to voluntarily offset their emissions.

To ensure the integrity of carbon credits and the projects that generate them, there are various mechanisms in place. These include validation and verification requirements, which assess the eligibility and quantification of emission reductions or removals from offset projects. Registries are used to track the ownership and retirement of carbon credits to prevent double counting. Third-party auditors are also involved to ensure impartiality and limit conflicts of interest.

Overall, carbon credits play a crucial role in incentivizing and financing projects that reduce greenhouse gas emissions. They provide a market-based approach to addressing climate change and can help countries and companies meet their emission reduction targets.



###Response 3:
Carbon credits are important for several reasons:

1. Climate Change Mitigation: Carbon credits help in reducing greenhouse gas emissions, which are the primary cause of climate change. By incentivizing and financing projects that reduce emissions, carbon credits contribute to mitigating climate change and its impacts.

2. Transition to a Low-Carbon Economy: Carbon credits play a crucial role in facilitating the transition to a low-carbon economy. By creating a market for emissions reductions, they encourage the development and deployment of renewable energy projects, energy efficiency initiatives, and other sustainable practices. This helps to shift away from fossil fuel-based industries and towards cleaner and more sustainable alternatives.

3. Encouraging Innovation and Investment: The availability of carbon credits provides financial incentives for businesses and organizations to invest in innovative technologies and practices that reduce emissions. This can spur technological advancements, research and development, and the adoption of sustainable practices across various sectors.

4. Supporting Sustainable Development: Many carbon offset projects, particularly in developing countries, have co-benefits beyond emissions reductions. These projects often contribute to sustainable development by providing access to clean energy, improving local livelihoods, protecting biodiversity, and promoting social and economic well-being in communities.

5. Corporate Social Responsibility: Carbon credits offer companies and organizations an opportunity to demonstrate their commitment to environmental sustainability and corporate social responsibility. By offsetting their own emissions, they can showcase their efforts to reduce their carbon footprint and contribute to global climate goals.

6. Compliance with Regulations and Targets: In compliance markets, carbon credits are essential for meeting mandatory emission reduction targets set by international agreements or governmental regulations. They provide a mechanism for companies and countries to achieve their emission reduction obligations and avoid penalties or sanctions.

7. Consumer Demand and Reputation: Increasingly, consumers are becoming more conscious of the environmental impact of the products and services they choose. Companies that demonstrate their commitment to reducing emissions and offsetting their carbon footprint through the use of carbon credits can enhance their reputation and attract environmentally conscious consumers.

Overall, carbon credits are important tools in the fight against climate change. They provide a market-based approach to reducing emissions, driving innovation, supporting sustainable development, and helping organizations meet their environmental goals.


Time taken: 113.71623640299367 seconds






As you can see, the bot loses context of the conversation because the first response is extremely wordy and gives way more information than is required by the prompt. This behaviour is consistent for tests done on any version greater than 0.8.56. Any versions lower than 0.8.56 maintain context very well.

**Comment by Disiok** [comment]
Hmm it really shouldn't that slow. How many documents did you index? Are you using a dedicated vector DB?

**Comment by ElioErrico** [comment]
Hello, thanks for your answer.

I used more or less the same criteria on the documentation at following link:
[https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents.html](url) 
but not using the `top_agent` and the `FnRetrieverOpenAIAgent` method because not working with `chat` method.

Now i have 9 documents very short (about 500 tokens each document).
(_I can not use only one vector store because the documents contains different informations but with very similar semantics_)
Each document have is own vector store index.

Here is the logic of my code:

1. Initialization of empty tool list and empty nodes
2. create a vector index one for each document 
3. create a vector query engine on for each  vector index
4. create a QueryEngineTool one for each vector query engine
5. append the QueryTool to the list of tools
6. create the agent that will use all this query tools
7. chat with the agent.

This is the relevant code:

```
# 1 CREATE EMPTY LIST OF TOOLS AND NODES
node_parser = SimpleNodeParser.from_defaults()
tools_to_be_used=[]
all_nodes = []

for idx, documento in enumerate(lista_documenti): 
    nodes = node_parser.get_nodes_from_documents(dizionario_documenti[documento]) # estraggo i (nodi) dai documenti specificati da 'city_docs[wiki_title]
    all_nodes.extend(nodes)

# 2 CREATE A VECTOR STORE INDEX ONE FOR EACH DOCUMENT
    if not os.path.exists(f"./data/{documento}")
        vector_index = VectorStoreIndex(nodes, service_context=service_context) 
        vector_index.storage_context.persist(persist_dir=f"./data/{documento}") 
    else: 
        vector_index = load_index_from_storage(
            StorageContext.from_defaults(persist_dir=f"./data/{documento}"),
            service_context=service_context,
        )

# 3 CREATE A VECTOR QUERY ENGINE ONE FOR EACH INDEX
    vector_query_engine = vector_index.as_query_engine()

# 4  CREATE A QUERY TOOL FOR EACH VECTOR QUERY ENGINE
    query_engine_tool =QueryEngineTool(
            query_engine=vector_query_engine,
            metadata=ToolMetadata(
                name=f"{documento}_vector_tool",
                description=f"Utilizza questo tool per qualsiasi domanda riguardante '{documento}, esempi: Diagnostica e risoluzione errore,  Conclusioni analisi'",
                ))
    
# 5 APPEND THIS TOOL TO THE LIST OF TOOL
    tools_to_be_used.append(query_engine_tool)

# 6 CHAT WITH THE AGENT
llm = OpenAI(model="gpt-3.5-turbo-0613",temperature=0)
agent = OpenAIAgent.from_tools(
    tools_to_be_used, llm=llm, verbose=True
)

```
