### ISSUE TITLE
[Question]: Merge nodes using start and end indexes

### ISSUE THREAD

**Issue by philipk19238** [run-llama/llama_index#9104]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How do I merge nodes that are close to each other without doing a graph search, given start + end char indexes are deprecated?

**Comment by logan-markewich** [comment]
close as in textually? Semantically?

I would set the overlap to be 0, and since the nodes are returned in order, you can merge that way

Another way is to parse nodes hierarchically 
https://docs.llamaindex.ai/en/stable/examples/retrievers/auto_merging_retriever.html#parse-chunk-hierarchy-from-text-load-into-storage

**Comment by philipk19238** [comment]
I think your approach makes sense, might have to inherit from TextNode and add a sequential_index attribute. My use case is during semantic retrieval for RAG where if multiple "nearby (start/end char_index)" are pulled then it would be merged into a singular chunk and sorted in sequential order before injected into the context window.

Hierarchical chunks is interesting - do you notice that it improves recall? Would be more expensive to implement since I do a lot of metadata tagging + embedding.

**Comment by logan-markewich** [comment]
hmm embedding costs will be the same, slightly more storage (docstore gets bigger), but that notebook will automate this exact use-case for you. Maybe give it a try with a few sets of documents and compare
