### ISSUE TITLE
[Question]: Multi MetadataFilters using Chroma

### ISSUE THREAD

**Issue by mphipps2** [run-llama/llama_index#9182]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to apply multiple ExactMatchFilters inside my VectorIndexRetriever using Chroma. I found an example of this using Redis here: https://docs.llamaindex.ai/en/latest/examples/vector_stores/RedisIndexDemo.html#. The syntax shown there looks like this:

query_engine = index.as_query_engine(
    similarity_top_k=3,
    filters=MetadataFilters(
        filters=[
            ExactMatchFilter(key="user_id", value="12345"),
            ExactMatchFilter(key="favorite_color", value="blue"),
        ]
    ),
)

However, when I try the same sort of thing on my Chroma index I get the error: 

    raise ValueError(f"Expected where to have exactly one operator, got {where}")
ValueError: Expected where to have exactly one operator, got {'key1': 'val1', 'key2': 'val2'}

That's using the same format for the retriever as shown in the example. Is there a different syntax needed for multi-filters using Chroma?

**Comment by mphipps2** [comment]
This is my retriever:

`
        retriever = VectorIndexRetriever(
            index=index,
            similarity_top_k=10,
            filters=MetadataFilters(
                filters=[
                    ExactMatchFilter(key="key1", value="value1"),
                    ExactMatchFilter(key="key2", value="value2"),
                ]
            ),
`

If I remove either of the ExactMatchFilters it works with the single filter. Using multi-filters causes this error from Chroma:

`
llama_index/indices/vector_store/retrievers/retriever.py", line 86, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
llama_index/indices/vector_store/retrievers/retriever.py", line 164, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
llama_index/vector_stores/chroma.py", line 236, in query
    results = self._collection.query(
chromadb/api/models/Collection.py", line 283, in query
    valid_where = validate_where(where) if where else {}
/chromadb/api/types.py", line 318, in validate_where
    raise ValueError(f"Expected where to have exactly one operator, got {where}")
ValueError: Expected where to have exactly one operator, got {'Client': 'Exxon', 'Month': 'April'}
`

Any help here greatly appreciated

**Comment by hatianzhang** [comment]
@mphipps2 can you show us the full code maybe in colab.
Want to understand how you init Chroma vector index

**Comment by chunyat** [comment]
I too am having the same issue trying to use multiple filters for the Chroma vector store. 

Looking into `chroma.py`, it seems that `_to_chroma_filter` is not properly handling multiple filters. According to the [Chroma docs](https://docs.trychroma.com/usage-guide#using-where-filters) this is how one needs to handle multiple exact match filters (or the `"$eq"` operator in Chroma) assuming just the simplest case of all `and` operators only and not even considering mixing in `or` operators:

```
{
    "$and": [
        {
            "metadata_field": {
                "$eq": <Value>
            }
        },
        {
            "metadata_field": {
                "$eq": <Value>
            }
        }
    ]
}
``` 

which can simplify to:

```
{
    "$and": [
        {
            "metadata_field": <Value>
        },
        {
            "metadata_field": <Value>
        }
    ]
}
``` 

Clearly, `_to_chroma_filter` is not properly converting multiple filter dictionary keys into the most straightforward case of an `and` operator for Chroma.

I understand there is a caveat that only `ExactMatchFilter`s are supported and supporting more advanced expressions is still a todo, but defining the `filters` property as `List[ExactMatchFilter]` in the `MetadataFilters` class is giving the false signal that at the very least the most likely use case of all `and` operators is supported if you provide a list containing more than 1 `ExactMatchFilter`. It might work for other vector stores, but apparently not for Chroma.

We also can't even try to construct our own advanced filter expression to pass to the `filters: List[ExactMatchFilter]` property in `MetadataFilters` for our vector store of choice (in this case Chroma) because of the strict pydantic typing accepting only `int`, `float` or `str` for the `value` of `ExactMatchFilter` - so we can't even do:

```python
ExactMatchFilter(key="$and", value=[{"metadata_1": "value_1"}, {"metadata_2": "value_2"}]}
```

So it would seem that the only workaround for now would be to directly modify `_to_chroma_filter` in `chroma.py`?

**Comment by hatianzhang** [comment]
@chunyat that is great advice.
Different vector store would have different syntax for supporting different filters. Our current filters supporting is pretty trieval.
For this case, we should modify it directly in `_to_chroma_filter` if number of filters > 1.
So that Chroma can get ```ExactMatchFilter(key="$and", value=[{"metadata_1": "value_1"}, {"metadata_2": "value_2"}]}
```

For more complicated filter cases, our side need more desing

**Comment by chunyat** [comment]
@hatianzhang I agree that there would be too many different syntax to consider if we try to support all the more complicated filter cases for each vector store.

I am not sure how feasible it would be, but perhaps the `MetadataFilters` class could be modified to allow users to construct and add their own advanced filtering syntax? 

This is so that it would be up to each user to learn the filter syntax of their own chosen vector store and the `MetadataFilters` class only needs to pass the whole `where` filter constructed by the user directly to the vector store object.

**Comment by hatianzhang** [comment]
pls check out https://github.com/run-llama/llama_index/pull/9194
put a quick fix

**Comment by mphipps2** [comment]
This is great, guys. Thank you! That patch works well on my end.

Also think @chunyat's suggestion to somehow allow users to provide advanced filtering syntax is a good one, as long as it doesn't break things elsewhere. Not having that advanced filtering is a significant constraint at the moment

**Comment by hatianzhang** [comment]
check out https://github.com/run-llama/llama_index/pull/9216
which refactor MetadataFilter

**Comment by mphipps2** [comment]
Reopening this to ask about support for multi-filter, single-key. 

eg: key="Month", value=["March", "October"] with an OR filter condition and an IN operator
or another case: 
eg: key="Day", value=[7, 14] with an AND filter and operators [GTE, LTE]

I don't believe the updated solution allows for something.

Using Chroma, I have a solution for the first case working by: 

1) vector_stores/types.py
`
class MetadataFilter(BaseModel):
    key: str
    value: Union[StrictInt, StrictFloat, StrictStr, List[Union[StrictInt, StrictFloat, StrictStr]]]
    operator: FilterOperator = FilterOperator.EQ
`

2) vector_stores/chroma.py
`
def _transform_chroma_filter_operator(operator: str) -> str:
    """Translate standard metadata filter operator to Chroma specific spec."""
    if operator == "!=":
        return "$ne"
    elif operator == "==":
        return "$eq"
    elif operator == ">":
        return "$gt"
    elif operator == "<":
        return "$lt"
    elif operator == ">=":
        return "$gte"
    elif operator == "<=":
        return "$lte"
    elif operator == "in":
        return "$in"
    else:
        raise ValueError(f"Filter operator {operator} not supported")
`

3) vector_stores/chroma.py
`
def _to_chroma_filter(
    standard_filters: MetadataFilters,
) -> dict:
    """Translate standard metadata filters to Chroma specific spec."""
    filters = {}
    filters_list = []
    condition = standard_filters.condition or "and"
    condition = _transform_chroma_filter_condition(condition)

    if standard_filters.filters:
        for filter in standard_filters.filters:
            if filter.operator:
                operator = _transform_chroma_filter_operator(filter.operator)
                # Handle list values for 'in' operator
                if filter.operator == FilterOperator.IN and isinstance(filter.value, list):
                    filters_list.append({filter.key: {"$in": filter.value}})
                else:
                    filters_list.append({filter.key: {operator: filter.value}})
            else:
                # Assuming default behavior for filters without an explicit operator
                filters_list.append({filter.key: filter.value})

    if len(filters_list) == 1:
        # If there is only one filter, return it directly
        return filters_list[0]
    elif len(filters_list) > 1:
        # Combine multiple filters based on the specified condition
        filters[condition] = filters_list

    return filters
`

And then this gets initialized like this:

`
metadata_filters = MetadataFilters(
    filters=[
        MetadataFilter(key="Month", value=["September", "October"], operator=FilterOperator.IN)
    ],
    condition=FilterCondition.OR
)
`

Can we implement support for something like this? This case looks easy to add. I'd really like a way to handle something like this as well but may take more effort:

eg: key="Day", value=[7, 14] with an AND filter and operators [GTE, LTE]
