### ISSUE TITLE
[Question]: Retrieval similarity threshold

### ISSUE THREAD

**Issue by debraj135** [run-llama/llama_index#9355]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there any way to specify a cosine similarity threshold in addition to the `similarity_top_k` when using a `VectorStoreIndex` as `index.as_query_engine(...)`?

**Comment by logan-markewich** [comment]
Yes, as a node-postprocessor

```python
from llama_index.postprocessor import SimilarityPostprocessor

postprocessor = SimilarityPostprocessor(similarity_cutoff=0.7)

query_engine = index.as_query_engine(similarity_top_k=2, node_postprocessors=[postprocessor ])
```

Source:
https://docs.llamaindex.ai/en/stable/module_guides/querying/node_postprocessors/root.html#node-postprocessor

**Comment by Matt-Scheetz** [comment]
@logan-markewich  I've tried the above solution, testing a really high cutoff: 0.9. But I'm still getting a response with sources having score of 0.812xxxx and 0.737xxxxx. It is answering the question correctly, but i was hoping to have it not be able to answer because no nodes were above the 0.9 score cutoff

**Comment by logan-markewich** [comment]
@Matt-Scheetz Seems to work for me

![image](https://github.com/run-llama/llama_index/assets/22285038/4f054118-097a-468f-ab6b-d5fc4cb2ba10)

**Comment by Matt-Scheetz** [comment]
Thanks, had a type-o on my end.
