### ISSUE TITLE
[Question]: Different numbers of embeddings with the same local embedding model

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#9413]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I’m following up on this question which was closed before I had the time to add my code: https://github.com/run-llama/llama_index/issues/9272

I get very different numbers of embeddings depending on whether I use an explicit text_splitter or not.

Using the attached graham file and the basic BAAI/bge-small-en embedding model
[graham.txt](https://github.com/run-llama/llama_index/files/13612397/graham.txt), 

Running this 

```
from llama_index.embeddings import HuggingFaceEmbedding
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en", max_length=512)
service_context = ServiceContext.from_defaults(
    llm=llm, 
    embed_model=embed_model, 
)
```

gives me 18 embeddings

```
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.09it/s]
Generating embeddings: 100%|███████████████████████████████████████████████████████████| 18/18 [00:06<00:00,  2.86it/s]
```

Running this

```
from llama_index.text_splitter import TokenTextSplitter
from transformers import AutoTokenizer
text_splitter = TokenTextSplitter(
    chunk_size=512,
    tokenizer=AutoTokenizer.from_pretrained("BAAI/bge-small-en").encode,
)

service_context = ServiceContext.from_defaults(
    llm=llm, 
    embed_model="local:BAAI/bge-small-en", 
    text_splitter=text_splitter,
)
```
gives me 93 embeddings (and notice the error message)
```
Parsing nodes:   0%|                                                                             | 0/1 [00:00<?, ?it/s]
Token indices sequence length is longer than the specified maximum sequence length for this model (16918 > 512). Running this sequence through the model will result in indexing errors
Parsing nodes: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.95s/it]
Generating embeddings: 100%|███████████████████████████████████████████████████████████| 93/93 [00:07<00:00, 11.94it/s]
```

I am basically just trying to use a local embedding model other than OpenAi, I was originally experimenting with e5-multilingual-large, but I get the same problem with bge-small-en. So what is the correct way to setup a local embedding?

**Comment by logan-markewich** [comment]
Dug into this more as the difference is much more egregious with BGE

A few notes on initial behaviour btw
- Your first code sample that generates 18 embeddings is using chunk_size=1024, a SentenceSplitter, and a gpt-3.5-turo tokenizer
- You second sample that generates 93 embeddings is using chunk_size=512, a TokenTextSplitter, and a huggingface BGE tokenizer
- The "warning" about ` (16918 > 512)` is just a standard warning in huggingface. We counted tokens for a sequence that was longer than 512, which is fine, we are counting to split tokens

Now, the real bug here is happening in that the huggingface tokenzier always appends the `[CLS]` and `[SEP]` tokens to the start end end of each tokenization call.

In the `TextTokenSplitter`, we are adding up individual words until their token count is over 512. However, now it's counting each word as 3 tokens instead of, underfilling to an average chunk size of ~270, creating many more embeddings.

So, I need to go and figure how to (nicely) handle the token counting for huggingface tokenizers

**Comment by logan-markewich** [comment]
as a temp workaround though, really you can just do

```
from llama_index.embeddings import HuggingFaceEmbedding
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en", max_length=512)
service_context = ServiceContext.from_defaults(
    llm=llm, 
    embed_model=embed_model, 
    chunk_size=512
)
```

Whic uses a chunk_size=512, SentenceSplitter, and gpt-3.5-tokenizer, which is totally fine to do. The actual difference in token counts between BGE and gpt-3.5 is minuscule, and the embedding model will truncate, but the LLM will not, so its usually better to make the LLM happy :)

**Comment by stephanedebove** [comment]
@logan-markewich is gpt-3.5-tokenizer under MIT or Apache2 licence and 100% free to use on my local computer? Basically why I’m doing all this instead of using the default models is that I need models with three conditions : 1/ free to use 2/ licence for commercial projects 3/ performance not too bad with non-english languages.

**Comment by logan-markewich** [comment]
@stephanedebove tiktoken is MIT licensed, free to use as far as I know

https://github.com/openai/tiktoken/blob/main/LICENSE
