### ISSUE TITLE
[Question]: when using SentenceTransformerRerank, could we specify a folder where the reranker model should be downloaded to?

### ISSUE THREAD

**Issue by haolxx** [run-llama/llama_index#9718]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

when using SentenceTransformerRerank, could we specify a folder where the reranker model should be downloaded to? Thanks!

from llama_index.postprocessor import SentenceTransformerRerank
rerank = SentenceTransformerRerank(
            top_n=10, 
            model="cross-encoder/ms-marco-MiniLM-L-2-v2",
            # folder_name = "./rerank_models/",
            device=device
        )

**Comment by logan-markewich** [comment]
Nope. Although you could download it beforehand and pass in a path for the model name

**Comment by haolxx** [comment]
> Nope, you can't. Although you could download it beforehand and pass in a path for the model name

It worked! Thanks!

**Comment by TheMellyBee** [comment]
Since the Sentence Transformers has a cache_folder parameter could this be added to this rerank? It would just need a pass through parameter. Similarly with the local_files_only. 

https://sbert.net/docs/package_reference/cross_encoder/cross_encoder.html#id1 
https://sbert.net/docs/package_reference/sentence_transformer/SentenceTransformer.html#sentence_transformers.SentenceTransformer
