### ISSUE TITLE
[Bug]: didn't release GPU memory when generating embedding batch by batch

### ISSUE THREAD

**Issue by rayneznv** [run-llama/llama_index#9875]
### Bug Description

Hi, 
I met the OOM issue when building vector index. GPU Memory usage keep increasing while generating embedding per batch.
I found the memory would not be released after generated a batch of embedding.
Could you help to check and fix it? Thanks a lot.

### Version

0.9.26

### Steps to Reproduce

It takes more than 48GB GPU memory when build index with more than 2048 * 100 nodes using embed model "jinaai/jina-embeddings-v2-base-en".

**Comment by logan-markewich** [comment]
@rayneznv I've never seen this before. I just tried to replicate this, and the GPU memory held steady at ~12.3GB with a batch size of 40 (the jump to 12GB was because I killed and restarted the embeddings to use a larger batch size)

https://colab.research.google.com/drive/1WC_3AQl2tVx2rciCp7SnjXhu9VPB2iQk?usp=sharing

![image](https://github.com/run-llama/llama_index/assets/22285038/16234f1f-99d5-4b49-ac19-cb2ce1f3a0b6)

**Comment by rayneznv** [comment]
> @rayneznv I've never seen this before. I just tried to replicate this, and the GPU memory held steady at ~12.3GB with a batch size of 40 (the jump to 12GB was because I killed and restarted the embeddings to use a larger batch size)
> 
> https://colab.research.google.com/drive/1WC_3AQl2tVx2rciCp7SnjXhu9VPB2iQk?usp=sharing
> 
> ![image](https://private-user-images.githubusercontent.com/22285038/294711032-16234f1f-99d5-4b49-ac19-cb2ce1f3a0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MjMyNzUsIm5iZiI6MTcwNDYyMjk3NSwicGF0aCI6Ii8yMjI4NTAzOC8yOTQ3MTEwMzItMTYyMzRmMWYtOTlkNS00YjQ5LWFjMTktY2IyY2UxZjNhMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDEwMjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZGExOWVmMmViZjdjOTI2YTZmYzYxNjg1NTIzZDI3MWExOGRmNmMwY2M4NTA3YjJjNGRiOTAyZmIzYmQ3MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xY74ilx7y_exl_HVXJC_t4iAiMQ20muKzKQLuOqsEow)

Hi @logan-markewich,
Thanks for your quick reply.
it works well when using replicates of same text to generate embedding in your sharing code. But if I use texts with different word and length, it will report OOM error. 
https://colab.research.google.com/drive/1uBggAidg9t-tuT9yoIHywx3PIWuQJ1El?usp=sharing
![image](https://github.com/run-llama/llama_index/assets/148318354/ce6de47e-6b31-426b-be23-c77a44c57d1d)

**Comment by logan-markewich** [comment]
I think this is just a batch size/max length issue. Since jina embeddings can take longer sequences than most embedding models, it also uses much more memory. 

Models only allocate memory for sequence lengths once they encounter them. So it might read a sequence that's 400 tokens, allocate memory for that, read another that's 500 tokens, and allocates another 100 tokens worth of memory. Basically, it's constant up to the longest sequence the model has seen.

For example, this worked for me (ignore the previous memory bumps, that was me figuring this out lol)
![image](https://github.com/run-llama/llama_index/assets/22285038/f3c2152e-0811-4667-bbb9-3e4aa0f5d527)

Going to close this out for now -- I suggest adjusting the max length and batch size to fit on your GPU.
